### ISSUE TITLE
GUI/undo tab: add possibility to save current state

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#101]
Add to Undo tab the possibility to:
1) save the current state
2) revert to saved state

This allows the user to experiment and return to the state he had before starting to experiment (and mimics undo several steps). Important is that the GUI saves the path where the state is saved on disk, save it as part of the sdcMicro object or allow the user to specify this path himself.

**Comment by bernhard-da** [comment]
hi, could you please test and report, if everything works

**Comment by thijsbenschop** [comment]
Thanks! Yes, this is what I had in mind. We will need to change the captions and text a bit. 
A few ideas for enhancements: 
1) Can we have a browse button for setting the file? This would be easier than manually typing or pasting a path.
2) What is the suggested path? The directory where the GUI is saved? Can this be replaced with the current working directory or left blank?
3) While reloading, the browse button could be removed, since one can copy paste the path from above. Even better would be if the path would already be suggested there.

**Comment by bernhard-da** [comment]
ad 1) no. Initially I tried with package `shinyFiles` which would have exactly what you described. Unfortunately this package has some issues, one of them being that it doesn't work with the way this (complex) shiny app is implemented. Unless the `shinyFiles` packages updates, there is no way to do so and the manual input is the best way to get a path

ad 2) it is actually `getwd()`

ad 3) I do not understand. You could have potentially saved many problem instances in different places. How would you know which one you want to reload?

**Comment by thijsbenschop** [comment]
Thanks!
ad 2) for me it was the path to the Shiny files:
![schermafbeelding 2016-10-31 om 22 21 29](https://cloud.githubusercontent.com/assets/8253935/19872118/74d4c312-9fb8-11e6-8b4e-cbbee825ebd0.png)
Does wd get set to this in the GUI? Upon closing the GUI, my wd is the one from which I launched R.

ad 3) Ok, my understanding here was that the user would only do this once to revert after messing up the data. But I agree that it can also be used several times. Should we then also list the paths to all instances in the current GUI session?

**Comment by bernhard-da** [comment]
2) depends really on how you start the gui. in `textInput()` from shiny you can enter a placeholder, which I set to `getwd()`. I do not really know what could be a better suggestion here.

3) no, I would just list the last exported file (current behaviour) because this is the file that is most likely to be imported.

**Comment by bernhard-da** [comment]
current solution works good.
