### ISSUE TITLE
Bug: racing condition

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#102]
Currently we experience in several instances a so-called racing condition in the GUI. Refreshing the page in the browser solves this. Any instance of this behavior can be uploaded to this issue. A report should include the exact location in the GUI (screenshot), the code from the reproducibility tab and, if possible, the data used.

**Comment by thijsbenschop** [comment]
I just experienced it with the testdata dataset trying to specify the path to export the report (see screenmovie 8 on Box). Also, after every character I enter, I have to reclick into the box to enter the next character, since the cursor disappears after each character (see screenmovie 9 on Box). This isn't the case if I enter the path name in the undo tab.

**Comment by bernhard-da** [comment]
Hi. Thx for reporting. Please test again and report back, if the issue has been solved.

**Comment by mwelch750** [comment]
Tested on export of sdcProblem. Racing condition appears to be solved.
