### ISSUE TITLE
Bug: names attribute must be the same length as vector

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#103]
In several instances the following error occurs in the GUI: names attribute must be the same length as vector. Any instance of this behavior can be uploaded to this issue. A report should include the exact location in the GUI (screenshot), the code from the reproducibility tab and, if possible, the data used.

**Comment by thijsbenschop** [comment]
I just experienced the name length errror, while testing with caseA.dta. I was converting numeric variables to factor:
![schermafbeelding 2016-11-28 om 14 27 19](https://cloud.githubusercontent.com/assets/8253935/20669904/cee43c1a-b576-11e6-8ce8-670da7c0ba99.png)

I cannot add the code from the reproducibility tab, since the GUI crashed (page doesn't refresh in browser) after a running condition on the microdata tab.

**Comment by thijsbenschop** [comment]
Will still try to reproduce now and add a complete reproducible example.

**Comment by bernhard-da** [comment]
after uploading the dataset, did you do anything else before trying to convert numeric to factors? if not, which variables did you convert? automatically or with custom breaks?

**Comment by thijsbenschop** [comment]
Just repeated the same steps, and it doesn't happen. Still it happened. Do you have any idea where it could come from?

First, I set some values to NA, then I converted them to factor (automatically)

**Comment by bernhard-da** [comment]
do you remember for which variable this happened?

**Comment by thijsbenschop** [comment]
In caseA.dta, there are many numeric variables that are actually categorical (almost all variables on an integer scale, except age). I took all these variables in a couple of subsets.

**Comment by thijsbenschop** [comment]
I also wonder why the GUI didn't reload any longer. I had to exit in the console.

**Comment by bernhard-da** [comment]
I just tried for 15 minutes to get an error such as you posted but I didn't manage. I'll wait for a reproducable example. 

As for the crashing: I can't tell as well If I do not know what the issue really is.

**Comment by thijsbenschop** [comment]
Hi,

thanks, I have also been trying to reproduce without result. The reality is though, that these errors keep occurring quite often, which is worrying. I hope to be able to come up with a reproducible example soon, so we can solve this issue.

**Comment by bernhard-da** [comment]
Well, it's a bit strange because if these errors occur often (which they do not do for me), it should actually be quite easy to generate a reproducable example.

**Comment by bernhard-da** [comment]
could it be that you were not trying to change numeric to factors but to modify existing factor variables because the reactive `curFactorVals()` is just defined within `ui_modify_change_factor` (which is the UI part to modify an existing factor).

**Comment by thijsbenschop** [comment]
Hi,

I completely understand your point. Since the error message only appears in the console, I often only realize after closing the GUI and cannot send an issue or reproducible example. I will be using the GUI and the console next to one another to track when the error occurs.

No, I didn't try to modify existing factor variables, but the racing condition started when I accidentally hit that button and quickly after the button I meant to hit. So perhaps by clicking the 'modify existing factor variables' button could have caused the problems.

**Comment by bernhard-da** [comment]
ok. please try that. i give up for now. i am not able to reproduce this.

**Comment by bernhard-da** [comment]
i added some debugging code. in the case that where this happens (as shown in https://github.com/alexkowa/sdcMicro/issues/103#issuecomment-263271077) the name of the invalid variable is printed to the R-prompt. this possibly helps to create a reproducable example.

**Comment by thijsbenschop** [comment]
Thanks, I will report here.

**Comment by thijsbenschop** [comment]
Hi, I just got the error but cannot see the variable name (see below). Where can I find the variable name of the variable causing this problem? Or are there different issues causing the same error and this was caused by a different one?

![image](https://cloud.githubusercontent.com/assets/8253935/21046247/00d4b89a-be04-11e6-81d8-ed2650682da4.png)

**Comment by bernhard-da** [comment]
it could be that you have some strange encodings in your variable names?

try the following: add 

```cat(paste0("var1=", dQuote(input$view_selvar1)," | var2=",dQuote(input$view_selvar2),"\n"))```

locally to line 504 in `ui_modify_data.R`. whenever you analyze variables (this is where the error happens), the variable names are printed to the promt and you can trace the offending variables.

**Comment by thijsbenschop** [comment]
Thanks, I'll do that.
