### ISSUE TITLE
GUI: Save variable selection in sdcMicro object set-up page

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#104]
If the user resets the problem (‘Click here to start from scratch’), all variable selections made previously are lost. Is there a way to have these selections preset? I’m thinking of a user who selected tens of variables, then realizes to have selected the wrong weight and has to redo the whole selection process. Then in the variable selection page, there could be a button to reset the choice.

**Comment by bernhard-da** [comment]
with the "table-setup" currently not possible. We will review this for a later-version.
