### ISSUE TITLE
GUI: add functionality for hierarchical files to GUI

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#105]
Please add the functionality to deal with hierarchical data files to the GUI by including the functions selectHouseholdData and mergeHouseholdData. An additional radiobutton 'Hierarchical data' on the microdata page after loading a dataset should be introduced: here the user can make two selections:
1) Prepare file for the anonymization of household level variables: here the user can create a datset containing only the household level variables and one record per household by dropping other variables and records. The user should be able to specify the household ID, household level variables and the household weight. A note should be added to make the user aware that the household level weights should be selected. If these aren't available, these should be created before reading in the data.
2) Merging an anonymized household level file into the full dataset for anonymization of the full dataset. Here the user should be able to read in the anonymized household level dataset (the original dataset is read in already at this stage) and specify the household ID (should be the same in both files, but this is guaranteed by using selectHouseholdData). Then the merged file replaces the file read in at the start.

**Comment by bernhard-da** [comment]
hi. please test the initial implementation and provide some feedback.

**Comment by bernhard-da** [comment]
should be ok.
