### ISSUE TITLE
GUI: add possibility to abort the process

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#106]
Add a button to cancel/abort a process? This can be useful if a process takes long. If R crashes for some reason and a error is shown in the console, will this than also always be communicated to the user? This is especially important if a method takes long.

**Comment by bernhard-da** [comment]
Unfortunately, this is not possible. The only way is to kill the shiny app (as it was with the old GUI, where the only way was to kill the entire GUI-process).

If in future new ways occur on how to implement this, we'll re-open this issue.
