### ISSUE TITLE
GUI: NaN in variables

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#107]
If I load the test dataset caseA.dta (on Box and attached), I convert the variable EDUCY to factor and tabulate the variable EDUCY, the tabulation shows that the variable contains 0 NA and 2159 NaN. See:
![schermafbeelding 2016-10-31 om 21 18 28](https://cloud.githubusercontent.com/assets/8253935/19870176/c016633e-9faf-11e6-8d8d-658a8b788218.png)
In R, Rstudio and STATA, these NaNs are NAs, see:
![schermafbeelding 2016-10-31 om 21 22 01](https://cloud.githubusercontent.com/assets/8253935/19870259/1d6386b6-9fb0-11e6-830e-830aec8877ee.png)
Since NAs in categorical variables play a crucial role in sdcMicro, we have to find out where these NA turn into NaN. Is this in the conversion to factor?

**Comment by thijsbenschop** [comment]
The problem seems indeed to be in the numeric to factor conversion. Before conversion the variable EDUCY has 2159 missings (NA):
![schermafbeelding 2016-10-31 om 21 27 01](https://cloud.githubusercontent.com/assets/8253935/19870448/e4a78d12-9fb0-11e6-96a1-53997da182d8.png)

**Comment by bernhard-da** [comment]
how did you load the data?

**Comment by thijsbenschop** [comment]
In R with read.dta from foreign

**Comment by thijsbenschop** [comment]
Indeed, with haven I get the following in R:
![schermafbeelding 2016-10-31 om 21 33 28](https://cloud.githubusercontent.com/assets/8253935/19870642/b5aaad18-9fb1-11e6-8aa5-0033a16ab17f.png)
Why did you opt for haven instead of foreign for STATA files?

**Comment by bernhard-da** [comment]
well, because `haven` is fast, under active development and almost always better than `foreign`. I don't think that this is an R problem but possibly a stata problem.

Another reason why importing datasets from other software is always a bit risky.

**Comment by mwelch750** [comment]
Hi,
Because foreign will not open stata 13+ files

**Comment by thijsbenschop** [comment]
Right, but then there is readstata13. We have to investigate why the missing values in STATA are imported wrongly. Perhaps this has to do with the type of missing in STATA. When users have STATA files, they need to be able to read them in correctly in the GUI.

**Comment by bernhard-da** [comment]
is there a difference in stata between NA an Nan? (R-terminology)? If not, we might just recode any `Nan` to `NA` in `readMicrodata()`?.

**Comment by bernhard-da** [comment]
btw, in Rstudio they are just displayed! as NA, but read as NaN as far as I know.

**Comment by cmachingauta** [comment]
Also possibly related to this issue, when I try to recode EDUCY, the NaN category takes the value of whatever is in the first category – in this case Category 0. It does not reflect the true number of NAs.
![image](https://cloud.githubusercontent.com/assets/7582929/19872096/6f4617d6-9f8e-11e6-8f62-ef5eb0d642be.png)
![image](https://cloud.githubusercontent.com/assets/7582929/19872100/7c58b7b2-9f8e-11e6-8a4a-35029df24939.png)
If I recode levels 0 and 1 and rename them “first”. Total Obs=6611.
![image](https://cloud.githubusercontent.com/assets/7582929/19872109/8590cd1a-9f8e-11e6-8fb1-0a785237d981.png)
Note how NaN also takes the same value
![image](https://cloud.githubusercontent.com/assets/7582929/19872120/8e1c8fd2-9f8e-11e6-89f0-37e5f80d80cd.png)

**Comment by bernhard-da** [comment]
another possibility would be to change in `varToFactor()` the current implementation of `as.factor(x)` to `factor(x, exclude=c(NA, NaN)`, see example below:

```
> x <- c(NA, sample(1:10), NaN); x
 [1]  NA   5   7   3   1   9   2   6   4  10   8 NaN
> table(as.factor(x), useNA="always")

   1    2    3    4    5    6    7    8    9   10  NaN <NA> 
   1    1    1    1    1    1    1    1    1    1    1    1 
> table(factor(x, exclude=c(NA, NaN)), useNA="always")

   1    2    3    4    5    6    7    8    9   10 <NA> 
   1    1    1    1    1    1    1    1    1    1    2 
```

**Comment by thijsbenschop** [comment]
I think the best option is to convert any NaNs to NA in order to also capture those variables that aren't converted to factor in the GUI.

**Comment by bernhard-da** [comment]
just pushed an update. please test and report back, if this issue can be closed.

**Comment by mwelch750** [comment]
Just tested. The problem seems to be solved.

**Comment by cmachingauta** [comment]
Hi Bernhard, thanks. I just tested and I see that the NAs are now excluded from the 'Select levels to recode/combine' box. Is it possible to have them show up there as well,  in case there is a situation where they need to be combined with another level or recoded as well? Thanks for adding the value labels.

**Comment by bernhard-da** [comment]
Hi, please check again with the latest changes which allow to recode also `NAs`. To do so, we add `NAs` as seperate level-category in `varToFactor()` and `globalRecode()` (if NA's exist). If everything works as expected, please let us know so that we can close this issue.
