### ISSUE TITLE
GUI / bug: unused arguments 

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#109]
We get the following error message in several places in the GUI:

![image001](https://cloud.githubusercontent.com/assets/8253935/19883018/0338463e-a012-11e6-88fb-790674d6b73a.png)

The data used is caseAlab.dta (see Box). I paste the code from the reproducibility tab below:

require(sdcMicro)

inputdata <- readMicrodata(path="/tmp/Rtmp4Dt1fv/762a9e678e92168c5c790805/CaseAlab.dta", type="stata", convertCharToFac=TRUE, drop_all_missings=TRUE)

inputdataB <- inputdata

 

## Convert a numeric variable to factor with user-specified breaks

inputdata <- varToFactor(obj=inputdata, var=c("AGEYRS"))

## Set up sdcMicro object

sdcObj <- createSdcObj(dat=inputdata,

        keyVars=c("REGION","DIST","MARITAL","AGEYRS"),

        numVars=c("INCTOTGROSSHH"),

        weightVar=c("WGTPOP"),

        hhId=c("IDP"),

        strataVar=NULL,

        pramVars=NULL,

        excludeVars=NULL,

        seed=0,

        randomizeRecords=FALSE,

        alpha=c(1))

 

## Recode variable

sdcObj <- groupAndRename(obj=sdcObj, var="DIST", before=c("District 1","District 2","District 3","District 4","District 5","District 6","District 7","District 8","District 9","District 10","District 11","District 12","District 13","District 14","District 15","District 16","District 17","District 18","District 19","District 20","District 21","District 22","District 23","District 24","District 25","District 26","District 27","District 28","District 29","District 30","District 31","District 32","District 33","District 34","District 35","District 36","District 37","District 38","District 39","District 40","District 41","District 42","District 43","District 44","District 45","District 46","District 47","District 48","District 49","District 50"), after=c("District 1_District 2_District 3_District 4_District 5_District 6_District 7_District 8_District 9_District 10_District 11_District 12_District 13_District 14_District 15_District 16_District 17_District 18_District 19_District 20_District 21_District 22_District 23_District 24_District 25_District 26_District 27_District 28_District 29_District 30_District 31_District 32_District 33_District 34_District 35_District 36_District 37_District 38_District 39_District 40_District 41_District 42_District 43_District 44_District 45_District 46_District 47_District 48_District 49_District 50"))

## Recode variable

sdcObj <- groupAndRename(obj=sdcObj, var="DIST", before=c("District 51","District 52","District 53","District 54","District 55","District 56","District 57","District 58","District 59","District 60","District 61","District 62","District 63","District 64","District 65","District 66","District 67","District 68","District 69","District 70","District 71","District 72","District 73","District 74","District 75","District 76","District 77","District 78","District 79","District 80","District 81","District 82","District 83","District 84","District 85","District 86","District 87","District 88","District 89","District 90","District 91","District 92","District 93","District 94","District 95","District 96","District 97","District 98","District 99","District 100"), after=c("District 51_District 52_District 53_District 54_District 55_District 56_District 57_District 58_District 59_District 60_District 61_District 62_District 63_District 64_District 65_District 66_District 67_District 68_District 69_District 70_District 71_District 72_District 73_District 74_District 75_District 76_District 77_District 78_District 79_District 80_District 81_District 82_District 83_District 84_District 85_District 86_District 87_District 88_District 89_District 90_District 91_District 92_District 93_District 94_District 95_District 96_District 97_District 98_District 99_District 100"))

## Recode variable

sdcObj <- groupAndRename(obj=sdcObj, var="DIST", before=c("District 101","District 102","District 103","District 104","District 105","District 106","District 107","District 108","District 109","District 110","District 111","District 112","District 113","District 114","District 115","District 116","District 117","District 118","District 119","District 120","District 121","District 122","District 123","District 124","District 125","District 126","District 127","District 128","District 129","District 130","District 131","District 132","District 133","District 134","District 135","District 136","District 137","District 138","District 139","District 140","District 141","District 142","District 143","District 144","District 145","District 146","District 147","District 148","District 149","District 150","District 151","District 152","District 153","District 154"), after=c("District 101_District 102_District 103_District 104_District 105_District 106_District 107_District 108_District 109_District 110_District 111_District 112_District 113_District 114_District 115_District 116_District 117_District 118_District 119_District 120_District 121_District 122_District 123_District 124_District 125_District 126_District 127_District 128_District 129_District 130_District 131_District 132_District 133_District 134_District 135_District 136_District 137_District 138_District 139_District 140_District 141_District 142_District 143_District 144_District 145_District 146_District 147_District 148_District 149_District 150_District 151_District 152_District 153_District 154"))

## set stratification variable

strataVar(sdcObj) <- "GENDER"

## Local suppression to obtain k-anonymity

sdcObj <- kAnon(sdcObj, importance=c(1,2,3,4), combs=NULL, k=c(3))

## reset stratification variable

strataVar(sdcObj) <- NULL

## calculating suda2 risk-measure

sdcObj <- suda2(obj=sdcObj, DisFraction=0.01)

**Comment by bernhard-da** [comment]
please test again with the latest updates and report back, if this issue can be closed.

**Comment by thijsbenschop** [comment]
Matthew, could you please test again, since I couldn't reproduce this issue?

**Comment by bernhard-da** [comment]
open a new issue referencing this one if this ever occurs again please.
