### ISSUE TITLE
GUI: enhancement: export script

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#110]
Can we add a button under the script on the view script page to download/export the script as .r or .txt?

**Comment by bernhard-da** [comment]
Hi. Could possibly be done. Before implementing, I have a general question. What do you think: Wouldn't it be better to have just one place (perhaps at the first page the user sees, the "about/info" page) where users may enter a path where all outputs (data, current problems, skript-files, ..) will be saved? This place should state the default value (`getwd()`) or the current path if changed?

This would allow to remove several input-fields, thus simplifying the UI.

**Comment by mwelch750** [comment]
I like this idea. I wonder if it belongs on the about page or microdata page?

**Comment by bernhard-da** [comment]
I'd do it on the "About page" (which we might rename to something else) because it is the first page a user will see but there might be better suggestions...

**Comment by mwelch750** [comment]
I am fine with the about page. Perhaps the about page could serve multiple purposes.
1) A brief intro for the app
2) A place to set up the environment before starting.
3) Perhaps even suggest a brief work flow for the user.

**Comment by bernhard-da** [comment]
@mwelch750 right, that's what I thought. 3) could be just a link (or reference) how to open the (to be written) vignette/manual about the GUI.

**Comment by bernhard-da** [comment]
please test if everything works as expected so that we can close this issue.

**Comment by thijsbenschop** [comment]
This is a great idea and saves the user a lot of work. We should add a note on each page where the user can export a file reminding him what the current save path is and where he can change it (on the about page). I will add that to the file with suggestions for descriptions, tips and help files.

**Comment by thijsbenschop** [comment]
Script export works for me as expected.

**Comment by bernhard-da** [comment]
Thx. I'll close this. But I do not think it is necessary to explain how to (change the export path) at each place where files are written to disk when we explain in in detail on the first page. Also, I do not think that it will be a typical behaviour that the output-path is changed very often.
