### ISSUE TITLE
GUI - Dealing with hierarchical data: summary of file

### ISSUE THREAD

**Issue by mwelch750** [sdcTools/sdcMicro#116]
On the screen for creating a household level file it may be useful to display a summary on the page after execution:

Variables that are now contained in the file
Number of observations in the file.

![image](https://cloud.githubusercontent.com/assets/7872305/19944424/40443406-a112-11e6-96e9-a91702f8655f.png)

**Comment by bernhard-da** [comment]
Good idea, have a look at the latest changes and report, if we can close this issue.

**Comment by mwelch750** [comment]
Good - thank you. You can close this one now.
