### ISSUE TITLE
GUI/TOR: Enhancement: Set seed for all probabilistic methods (e.g, PRAM)

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#118]
Allow setting a seed each time a probabilistic method is used (PRAM, etc.). This allows replicating results, even if the order of the methods is changed or a method is omitted. This can be done by editing the function and creating a new function argument, or just for the GUI by set.seed(). The seed should appear in the script (and list of applied methods).

**Comment by bernhard-da** [comment]
already implemented when the sdc problem is generated there is a seed-argument which is also shown in the code.

**Comment by thijsbenschop** [comment]
Right, but this doesn't take into account that the user would apply methods in a different order. After each method, the seed will be different, so the results of applying first pram and then noise addition would be different than the other way around. This is especially important if the users tries several options and uses 'undo' (one step). 'Undo' probably won't reset the seed.

**Comment by bernhard-da** [comment]
Agreed. But I think this is a feature for the next version as the typical user type in the GUI probably does not need to be absolutely reproducably over time.

**Comment by bernhard-da** [comment]
please re-open if required;
