### ISSUE TITLE
GUI/TOR: Enhancement, Add utility measures for continuous variables

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#119]
Add utility measures for continuous variables (in the information loss window: overview of summary statistics of each continuous variable (by categorical variable) before and after; possibility to run a simple regression (OLS/logistic) on the original and treated data correlation measures, possibly other measures (to be discussed). This is especially important to evaluate perturbative methods.

**Comment by bernhard-da** [comment]
As already explained on telco, we did not think it is very useful to add the regression comparison for several reason. First being the intended user type of the GUI (which we would make familiar with the R formula interface). Secondly the variable types may change and the results of the regression analysis may confuse more than being able to help evaluate perturbative methods.
