### ISSUE TITLE
GUI: Where to select ghost vars?

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#121]
Is it an idea to move the selection of ghost vars to the k-anonimity/local suppression menu? The user can then specify the ghost vars before doing local suppression. In this way the user is also reminded to specify the variables there.

**Comment by bernhard-da** [comment]
I prefer to leave this setting where it is because it is in fact changing/modifying the problem instance. We also already started the new description and will only move parts of the GUI if absolutely required which I do not think is the case here.

**Comment by bernhard-da** [comment]
current solution works good.
