### ISSUE TITLE
GUI/TOR: Enhancement: add option to prevent from recalculating the risk after each step

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#122]
Create an option to prevent automatic re-calculation of risk measures after every application of an SDC method. This would save time when rerunning a script or applying several methods in a row. This requires changing the sdcMicro functions (perhaps adding an additional parameter (e.g., recRisk = TRUE). (discussed this, only for the record)

**Comment by bernhard-da** [comment]
currently not possible, will check again for next major version.
