### ISSUE TITLE
GUI: Enhancement, add multiplicative noise

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#125]
In R it is easy to implement multiplicative noise. In the GUI this isn’t. Can we add multiplicative noise as an additional method for noise?

**Comment by bernhard-da** [comment]
possibly in the next version. we should try to get a new version on cran soon.

**Comment by matthias-da** [comment]
I would prefer to only use correlated noise as soon more than one variable is perturbed. Addititive or multiplicative noise just destroy the data set in a multivariate setting.
The correlated noise methods are implemented in sdcMicro. They should give much better results.
Only if for one single variable noise should be added/multiplied this method might be reasonable. For a future version is would be thus recommended to used correlated noise methods as soon more than 2 variables are chosen, additive or multiplicative for single variables.
