### ISSUE TITLE
GUI/TOR: Add number of violators to output

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#126]
In the l-diversity output window, summary statistics for the l-diversity risk measure are presented as well as an overview of the l-diversity measure for each records. Can we add a possibility to show the number of violators for a set level, e.g. those that have a l-diversity measure lower than 3. The number shown is the count of all records with 1 or 2-diversity. The level should be settable by the user. Alternatively, show the number of records that have only 1-diversity, 2-diversity, and 3-diversity.

**Comment by bernhard-da** [comment]
possible in the next version.
