### ISSUE TITLE
GUI/TOR: add more risk measures for continuous variables

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#127]
Add risk more measures for continuous variables (e.g. distance based measures, closest-neighbor), including measures that account for outliers.

**Comment by bernhard-da** [comment]
would need to implement them in sdcMicro as well. Any ideas which measures would be useful?

**Comment by orchardlucky** [comment]
Do we have functions in R which can measure the distance linkage disclosure risk (DLD) and the probabilistic linkage disclosure risk (PLD)?

**Comment by bernhard-da** [comment]
@orchardlucky 

is `?dRisk` and `?dRiskRMD` what you are looking for?

**Comment by orchardlucky** [comment]
@bernhard-da 

Thanks.

From the book by Matthias Templ.  There is one page below:
![image](https://user-images.githubusercontent.com/41325514/43457978-5aafdd6a-94c0-11e8-9aea-31ace698a50a.png)

so does it means dRisk is used to measure interval disclosure?dRiskRMD is used to measure  Distance-based record linkage? And so  how to measure the Probabilistic record linkage?

Best.

**Comment by bernhard-da** [comment]
hi,

`dRisk()` and `dRiskRMD()` both provide distance-based disclosure risk estimation, the difference being that dRisk() uses standard-deviation based intervals around observations while `dRiskRMD()` uses robust  mahalanobis distances. 

In sdcMicro, there is also the individual risk approach based on so-called super-population model assuming a negative-binomial distribution implemented (functions `indivRisk()`) or `measure_risk()`). there is no functionality available that computed risk measures based on probabilistic record linkage.
