### ISSUE TITLE
GUI/TOR: Check default values for all methods

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#128]
Check default values to be sure they are sensible for all methods (value used if parameter is not set). One example: for additive uncorrelated noise, alpha is by defaut 150 percent, wich means that the standard deviation of the noise is 1.5 times the standard deviation of the data. Depending on the variation in the original data, this can lead to large distortions, which might not always be necessary to protect the data.

**Comment by bernhard-da** [comment]
Agreed that this is a relatively high default value. But on the other hand, defaults should be chosen in a way that data are protected if they are not changed.

I'd suggest you file an issue for each method where you think the default value should be modified/changed.

**Comment by bernhard-da** [comment]
closing this. in case any parameters are missing, please file a seperate issue
