### ISSUE TITLE
GUI/bug: Cannot read STATA files (.dta) and SPSS (.sav) files

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#131]
In the latest version, it is not possible to upload a STATA file. It says ‘upload complete’ but the screen greys out and after refreshing the page, there is no dataset loaded. Tried with several datasets, for example the ones in the shared folder on Box.

![schermafbeelding 2016-11-10 om 20 21 50](https://cloud.githubusercontent.com/assets/8253935/20190855/64528182-a783-11e6-9ff7-bc9fa9825671.png)

**Comment by thijsbenschop** [comment]
Same happens if trying to load .sav files (SPSS):
![schermafbeelding 2016-11-10 om 20 24 20](https://cloud.githubusercontent.com/assets/8253935/20190947/c105777c-a783-11e6-9cf7-2fc14c4ebec9.png)

**Comment by bernhard-da** [comment]
should be fixed. please report back if i can close this.

**Comment by thijsbenschop** [comment]
Thank you for the quick fix, I can upload data again. 

I like the new buttons and am happy to see that they aren't as sensitive to the racing condition. I noticed though, that some of them aren't sufficiently large for the complete text (see screenshot, 4th and 9th buttons). Is it possible to introduce automatic line breaks depending on the column width, like it was with the radio buttons? 
![schermafbeelding 2016-11-10 om 20 53 12](https://cloud.githubusercontent.com/assets/8253935/20191942/067caed4-a788-11e6-9153-59761b14848f.png)

**Comment by bernhard-da** [comment]
we could either widen the sidebar (easy), shorten the text, make the font smaller ...

it also depends a lot on the device I think, i guess you're working on a small screen? this was troublesome in the old gui as well...

**Comment by thijsbenschop** [comment]
I think shortening the text would be best, not to take up more space. In this case we could shorten to 'Use subset of microdata' and 'Set specific values to NA'. Would that be sufficiently short?

**Comment by bernhard-da** [comment]
thx. committed. should be ok now.
