### ISSUE TITLE
Some text not displaying properly

### ISSUE THREAD

**Issue by cmachingauta** [sdcTools/sdcMicro#132]
See Microdata tab> Convert numeric variables to factor - Create a stratification variable

![image](https://cloud.githubusercontent.com/assets/7582929/20194026/b413784a-a75e-11e6-8fa0-a8b04f51bf8c.png)

![image](https://cloud.githubusercontent.com/assets/7582929/20194013/a621e3d4-a75e-11e6-8872-c8add58a2561.png)

**Comment by bernhard-da** [comment]
thx for reporting. copy/paste from word is a bad thing. could please file issues for any other pages where such things might occur? on my system, the characters looked ok so these things are difficult to spot.

also please report if this issue is fixed so we can close it. thx.

**Comment by cmachingauta** [comment]
Hi, 
I reinstalled and the issue still exists on the following pages
- Convert character/factor variables to numeric variables
- Modify existing factor variable
- Create a stratification variable

**Comment by bernhard-da** [comment]
thx. is all ok now?

**Comment by cmachingauta** [comment]
Thanks it looks good now.
