### ISSUE TITLE
Second thought on value labels

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#143]
Hi,

I mentioned in #134 that the value labeling problem was solved. Unfortunately, this isn't completely true. It works fine if the values are number 1,2,3,.... However, for example the variable URBRUR could be in the original file as follows: 0 - "URBAN", 1 - "RURAL", 9 - "OTHER". The data is read correctly in the 'labelled' class, but as soon as it is turned into a factor (with as_factor), it will be transformed into 1 - "URBAN", 2 - "RURAL", 3 - "OTHER". This is a problem for data users, since the codings from, for instance, the questionnaire won't be any longer accurate.

Ideally, we would convert the 'labelled' variables to 'factor' with the factor values being copied from the original variable (0 - "URBAN", 1 - "RURAL", 9 - "OTHER"). I couldn't get this to work. Do you have ideas how to achieve this? If this won't work, we will still need a function to export a do-file.

Also, somehow the argument labels = "values" in the as_factor function doesn't seem to work. I still get  the full labels as labels, whereas I would expect to get the underlying values. However, for the time being we should perhaps keep this as it is, since only in this way the labeling works now (since it takes the levels as value labels).
![schermafbeelding 2016-11-14 om 21 31 18](https://cloud.githubusercontent.com/assets/8253935/20314295/0c1d6fba-ab5a-11e6-8832-dee9726d0bbd.png)

**Comment by bernhard-da** [comment]
you could keep both levels and values by using `as_factor(x, levels="both")`. in this case the levels look something like `[0] URBAN`, `[1] RURAL`, `[9] Other` and you can write a simple function to split these levels once they have been exported

**Comment by thijsbenschop** [comment]
But wouldn't that look quite ugly in the GUI? I will experiment a little with that

**Comment by bernhard-da** [comment]
probably yes. perhaps its just easier to create a small function creating a do-file.

**Comment by thijsbenschop** [comment]
Yes, but the problem with the new values remains. In the example above, even when using "values", the factor variable becomes 1- "0", 2 - "1", 3 - "9". Writing a do-file isn't the problem, but the values should be mapped back. Also, using the "values" as levels, we won't capture recodes with new labels. 

So if we cannot get the original values back, there isn't any advantage over the current solution. So perhaps we have to stick with "both" after all.

**Comment by bernhard-da** [comment]
perhaps, but `both` is also likely not what you what since users may change the labels while recoding. I'd say until you come up with something, we'll leave everything as it is.
