### ISSUE TITLE
Generating report - error

### ISSUE THREAD

**Issue by cmachingauta** [sdcTools/sdcMicro#145]
Hi, I am getting the following error when I try to generate an external or internal report. Am I missing something? There is no report in the folder mentioned.

![image](https://cloud.githubusercontent.com/assets/7582929/20501283/439112ec-b007-11e6-8544-4f53aaab8237.png)

**Comment by bernhard-da** [comment]
hi, the `include_timing` argument comes from `knitr` and has nothing to do with `sdcMicro` per se. Please update all packages in your R-installation (especially `knitr`, `rmarkdown` and `evaluate`) and try again. The error should be gone.

if not, please attach a reproducible example by copying the code just before trying to generate the report.

**Comment by cmachingauta** [comment]
Thanks, I updated and it worked. 
I am wondering though, if there could be a button somewhere in the GUI, maybe on the About/Help page for the user do an auto-update of packages to match the ones used in the GUI and minimize the occurrence and reporting of similar errors. What do you think?

**Comment by bernhard-da** [comment]
Great to hear that it worked!

Well, it is possible but I do not think that this functionality should be part of the GUI. Users should always update periodically, especially in R where development is fast. Perhaps we should put a notice on the About page with instructions, e.g "if you run in any troubles, make sure that your R-installation is up to date using update.packages()."?

**Comment by cmachingauta** [comment]
Yes, that would be helpful for users.. Thanks

**Comment by mwelch750** [comment]
I think that is the most practical approach.
