### ISSUE TITLE
Question on 'restr' in addNoise

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#147]
Hi,

while adding text to the help balloons in the GUI, I had a look at addNoise.r and got a quick question on 'restr' in lines 149-160. As far as I see there is no stochastic part in the noise. Am I correct that cc is a scalar and all variables in x are multiplied with this same scalar after which (1-cc) times the respective column mean is added? So basically the method boils down to a deterministic linear transformation of which only wnoise is unknown to the intruder, which is the same for each variable (N is the size of the dataset)? I was wondering in how far this protects the data, but couldn't find any reference to this. Could you please direct me to a reference describing this algorithm and its uses?

Thanks!

```
  addNoise_restr <- function(x, noise) {
    N <- nrow(x)
    wnoise <- noise/100
    if (N < 500) {
      cc <- sqrt((N - 1 - wnoise)/((N + 1) * (1 + wnoise)))
    } else {
      cc <- sqrt((N - 1)/(N + N * wnoise - 1))
    }
    d <- (1 - cc) * colMeans(x, na.rm=TRUE)
    x <- cc * x + d
    x
}
```

**Comment by bernhard-da** [comment]
@matthias-da is the best one to comment on this

**Comment by matthias-da** [comment]
Unfortunately too long ago. The method was presented somehow around 1995-2000 at a conference from a German employee at Destatis if I remember well.
