### ISSUE TITLE
Question on clusters in microaggregation

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#150]
Both the sdcMicro help files and the chapter "Software Development for SDC in R" in "Privacy in Statistical Databases" state that "Clustering observations before applying microaggregation might be useful." I have been trying to think of situations where clustering would make a large difference to the results. Especially in cases of small groups (size 3), I wonder if the grouping algos and the clustering algos differ to such a point that cluster would cut through many groups and hence yielding a different result then would be the case without clustering. One would expect, depending on the selected algos, that the clustering and groupng algorithms do the same thing. Therefore, I was wondering whether you know about some experiments that looked into this issue and go a bit more into detail on the usefulness of clustering before microaggregation.

**Comment by bernhard-da** [comment]
@matthias-da is the best one to comment on this.

**Comment by matthias-da** [comment]
This depends on the method used. If one uses MDAV by thinking what MDAV is doing, then traditional clustering does not make much sense before, expect computation time would be likely reduced depending on the clustering algo used (k-means or hierarchical ca are quite fast, faster than MDAV). If other methods are chosen for microaggregation, e.g. PCA or the individual ranking method often applied in Germany, then clustering before makes sense.
