### ISSUE TITLE
microaggregation with single variable

### ISSUE THREAD

**Issue by sinanshi** [sdcTools/sdcMicro#152]
While performing micro-aggregation on a single variable data.frame, the method argument lost its effect due to the following [code](https://github.com/alexkowa/sdcMicro/blob/aa8ea849ab70c1ce331cf507e3bec33d4589b17a/R/microaggregation.R#L237)

```
microaggregation(data.frame(a=seq(10)), method="anything")
```
Not sure if this is intentional or not.

**Comment by bernhard-da** [comment]
Hi. Thx for reporting. The reason is that if only one variable needs to be microaggregated, there is basically only one way on how to form similar groups (which is sorting the data). Thus, the fast version `mafast()` is used in this case. I added however a note to the documentation.
