### ISSUE TITLE
'Set values to NA' button disappearing

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#153]
Hi,

I just experienced a problem with 'Recoding values to NA'. I use caseA.dta and try, immediately after loading, to set the value '99999' in the variable 'RELIG' to NA. However, the button disappears after selecting 99999, so I cannot set the values. After converting to factor, I still have the same problem. It seems a problem with specific values, since the button reappears after selecting some of the other values. See screenmovie10 and caseA.dta on Box and screenshot below with tabulation of factor variable RELIG.

![schermafbeelding 2016-11-28 om 08 26 51](https://cloud.githubusercontent.com/assets/8253935/20659694/862038ca-b545-11e6-8bb8-028c636efa5a.png)

**Comment by thijsbenschop** [comment]
The same happens with the values 2,3,4,5,6,7,9 and 99 for EMPTYP1, both as numeric variable and after converting to factor. Only the value '1' can be set to NA. Generally, it seems the button only appears for the first value in a variable.

**Comment by bernhard-da** [comment]
Hi. I can reproduce this. It happens only if you want to set values to `NA` by rule, right? I'll fix this later today.

**Comment by thijsbenschop** [comment]
Yes, indeed only by rule. Thanks

**Comment by bernhard-da** [comment]
above commit should fix this issue. please report back if we can close this.

**Comment by thijsbenschop** [comment]
thanks, it is solved now
