### ISSUE TITLE
Alignment of tabulation on set-up page

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#154]
On the set-up page, the user can look at tabulations of the variables. I'm using the file caseA.dta, in which I only selected household based on IDH (this shouldn't matter though) and converted all used variables to factor.

In case of few categories that fit on one line, it looks fine (e.g., REGION). The level and the frequency are nicely aligned:
![schermafbeelding 2016-11-28 om 21 48 35](https://cloud.githubusercontent.com/assets/8253935/20685390/88be357c-b5b4-11e6-9042-ee4c09e9e62a.png)

However, if the number of levels is larger and they do not fit on one line, the overview gets blurred. In the example of HHSIZE, the first two lines show the levels and the next two the frequencies, which are aligned though. Also one level (13) has a linebreak. 
![schermafbeelding 2016-11-28 om 21 45 41 1](https://cloud.githubusercontent.com/assets/8253935/20685487/eccbc656-b5b4-11e6-834e-b2d1e4f6cd0c.png)

In the example of DIST, the overview is completely destroyed (several lines of factor levels, several lines of frequencies). 
![schermafbeelding 2016-11-28 om 21 46 12](https://cloud.githubusercontent.com/assets/8253935/20685675/a07f4de4-b5b5-11e6-898d-78e193460a56.png)

This is well visible in IDH (values 1-2000), which cuts of after 99 levels and groups the remaining into (Other):
![schermafbeelding 2016-11-28 om 21 58 08](https://cloud.githubusercontent.com/assets/8253935/20685743/ebd9b658-b5b5-11e6-94bb-a993b4f70c61.png)

Is this system-dependent? Could you please have a look to improve the alignment of factor levels and frequencies?

**Comment by bernhard-da** [comment]
yes, this basically shows that variables with many, many unique values are probably not useful to be used as categorical key variables. such variables can be analyzed in detail in the explore data facilities. i do not see a way to improve this apart from displaying a maximum number of levels (and adding text) that x additional unique values exist but won't be displayed.

**Comment by bernhard-da** [comment]
do you think that this is better?

**Comment by thijsbenschop** [comment]
Thanks, I think this is a better way. I agree that a tabulation of IDH isn't useful, but a variable with 20 levels, like HHSIZE should be possible to tabulate.
