### ISSUE TITLE
Freeze of GUI

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#155]
after dismissing but not correcting invalid choice in SDC setup screen and subsequently trying to reset the dataset in the microdata window.

These steps illustrate the issue:
1) load the testdata
2) select 'sex' as cat key
3) select 'savings' as cat key
4) dismiss the error message, but don't correct
5) navigate to the 'Microdata' tab and click 'Reset microdata'
6) the GUI greys out and freezes (the usual warning message isn't shown), refreshing the page in the browser helps

**Comment by bernhard-da** [comment]
hi. i can reproduce this but it is a bit tricky. in fact, the GUI is not freezing, but the modal-window (popup) is displayed over the entire page which makes it seem as if the GUI was frozen. This is either a bug in the stylesheet (but I can still reproduce if I remove the custom stylesheet from ui.R) or in shiny itself. i'll try to come up with a fix.

**Comment by thijsbenschop** [comment]
Thanks, that explains why refreshing the browser solves this and no pop-up
is shown.

**Comment by bernhard-da** [comment]
hi, could you confirm that everything works after the latest changes?

**Comment by thijsbenschop** [comment]
Thanks, the issue is solved.
