### ISSUE TITLE
Some text still overlapping text-box borders

### ISSUE THREAD

**Issue by cmachingauta** [sdcTools/sdcMicro#159]
![image](https://cloud.githubusercontent.com/assets/7582929/20842496/b7ec15b6-b885-11e6-88bc-74e958785223.png)

Hi - Is it possible to shorten the text that is overlapping?  I had suggested some shorter text but it doesn't seem to have been merged. Thanks

**Comment by bernhard-da** [comment]
hi, please update to the latest version. your pull-request was merged (which included the change to "Convert numeric to factor", see  [here](https://github.com/alexkowa/sdcMicro/blob/sdcMicro_next/inst/shiny-examples/sdcGUI/controllers/ui_modify_data.R) (line 169)

**Comment by cmachingauta** [comment]
I see. I'll make the same change to line 855. It seems that's where this overlapping occurs.  Thanks

**Comment by bernhard-da** [comment]
should be fixed thanks to your pull request #160 .
