### ISSUE TITLE
GUI: PRAM (expert)

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#167]
After doing the following steps on caseA.dta, I want to use PRAM (expert), but get the error message 'Error:subscript out of bound'. The screen is jumping between the error message and the transition matrix. I want to use PRAM (expert) for another PRAM variable, I didn't use in the simple mode.

-	Load data
-	Set 99999 in RELIG, 99 in EMPTYP1, and 9999 in LIVESTOCK to NA
-	Create household level file (household id IDH and household level variables URBRUR, REGION, OWNHOUSE, OWNAGLAND, RELIG, LANDSIZEHA, TANHHEXP, TFOODEXP, TALCHEXP, TCLTHEXP, THOUSEXP, TFURNEXP, THLTHEXP, TTRANSEXP, TCOMMEXP, TRECEXP, TEDUEXP, TRESTHOTEXP, TMISCEXP, INCTOTGROSSHH, INCRMT, INCWAGE, INCFARMBSN, INCNFARMBSN, INCRENT, INCFIN, INCPENSN, INCOTHER, ROOF, TOILET, WATER, ELECTCON, FUELCOOK, OWNMOTORCYCLE, CAR, TV, LIVESTOCK, WGTHH, DIST, HHSIZE
-	Convert to factor: REGION, URBRUR, OWNHOUSE, OWNAGLAND, RELIG, DIST, HHSIZE, ROOF, TOILET, WATER, ELECTCON, FUELCOOK, OWNMOTORCYCLE, CAR, TV, LIVESTOCK
-	Setup SDC problem: 
o	categorical keys: URBRUR, REGION, HHSIZE, OWNAGLAND, RELIG; 
o	continuous keys: LANDSIZEHA, TANHHEXP, TFOODEXP, TALCHEXP, TCLTHEXP, THOUSEXP, TFURNEXP, THLTHEXP, TTRANSEXP, TCOMMEXP, TRECEXP, TEDUEXP, TRESTHOTEXP, TMISCEXP, INCTOTGROSSHH, INCRMT, INCWAGE, INCFARMBSN, INCNFARMBSN, INCRENT, INCFIN, INCPENSN, INCOTHER; 
o	pram variables: ROOF, TOILET, WATER, ELECTCON, FUELCOOK, OWNMOTORCYCLE, CAR, TV, LIVESTOCK; 
o	weight variable: WGTHH, 
o	remove: DIST.
-	Compute SUDA scores (sampling fraction is 0.01)
-	Explore other risk measures and risky observations
-	Top code HHSIZE at 14 (by recoding), replacement value is 14, will be deleted
-	Top code LANDSIZEHA at 40
-	Local suppression (k=2)
-	Undo last step
-	Local suppression (k=2, importance: URBRUR(3), REGION (2), HHSIZE (1), OWNAGLAND(5), RELIG(5))
-	Look up record IUDs of records with suppressed HHSIZE
-	PRAM all pram variables excepts LIVESTOCK with PRAM (simple)

**Comment by thijsbenschop** [comment]
Console output:

![image](https://cloud.githubusercontent.com/assets/8253935/21140914/c21271c6-c13a-11e6-9fdd-8f8dab398a29.png)

**Comment by bernhard-da** [comment]
sorry, I can't reproduce this. [Here](https://gist.github.com/bernhard-da/efcafc0da74d20ba16949ea8f15f1b54) is the log of what I did. Everything worked as expected.

Also I think you did something other than you have described because `output$pram_expert_transmat` is only evaluated in expert-mode for pram. I also have a saved the problem-instance just before applying pram that I can load and also then everything works as expected. In case you want to have this, I could send it to you.
