### ISSUE TITLE
GUI: summary page, compare numVars

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#168]
After adding noise to all expenditure variable (EXP), except TANHHEXP in caseA.dta (using additive noise, with noise level 10), I get instead of the Compare numVars overview the following error. Undoing the noise addition solves it and it reappears after reapplying noise addition. Could this be caused by a NA or NaN in the summary table for one of the variables?

![image](https://cloud.githubusercontent.com/assets/8253935/21140774/20e2376e-c13a-11e6-8759-4e7e034cc232.png)

**Comment by thijsbenschop** [comment]
Console output:
![image](https://cloud.githubusercontent.com/assets/8253935/21140944/d587e01a-c13a-11e6-8ea6-fad720a1b6f8.png)

**Comment by thijsbenschop** [comment]
Same happens for income, selecting all income variables (INC) except the total (INCTOTGROSSHH), I get:
![image](https://cloud.githubusercontent.com/assets/8253935/21141050/6619632e-c13b-11e6-9638-18fcdd2679b1.png)
```
## Adding stochastic noise
sdcObj <- addNoise(obj=sdcObj, variables=c("INCFIN","INCRMT","INCRENT","INCWAGE","INCPENSN","INCOTHER","INCFARMBSN","INCNFARMBSN","INCBONSOCALL"), noise=c(10), p=NA, delta=NA, method="additive")
```

**Comment by bernhard-da** [comment]
thx for reporting. fixed.
