### ISSUE TITLE
#172 isn't solved

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#173]
Hi,

I just tested with the fix for #172, but I'm still experiencing the same behavior (see below). If this is difficult to fix, I think we could also go without the var name in the title, since the pop-up occurs immediately after making the invalid choice. So typically the user would know what his/her last selection was.

![schermafbeelding 2017-01-10 om 20 57 22](https://cloud.githubusercontent.com/assets/8253935/21822971/a3b35fec-d779-11e6-96a4-b8621793b1fd.png)

**Comment by bernhard-da** [comment]
can't reproduce, works fine here.

![issue_173](https://cloud.githubusercontent.com/assets/5228437/21823410/2f4efd08-d77b-11e6-8614-325611393374.png)

**Comment by thijsbenschop** [comment]
Sorry, my mistake, I was looking in the branch sdcMicro_next, not the master. The issue is solved, thanks!

Shall we in future make merge requests to the master branch too, if any?

**Comment by bernhard-da** [comment]
everything should go into branch `next`. whenever we make a new cran-version, we'll merge this branch to the master branch.
