### ISSUE TITLE
Greying out of GUI if reading in Stata file with some missing variable labels

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#180]
HI,

Cathrine uploaded more test files on Box and added a weight variable to the Honduras files. This variable has no variable label. After loading the new file from Box (HND_2012_L2L.dta.dta) in the GUI, the screen greys out. After refreshing the browser, everything works as expected. The console shows: 

![image005](https://cloud.githubusercontent.com/assets/8253935/22244338/6b03ecea-e22b-11e6-882b-6bb69e903618.png)

It turns out that the missing variable label is read in as NULL. I added a fix to the extractLabels function that sets NULL values to NA (see #179). This solves the greying out upon reading in the data. 

However, if I want to load the page in the export menu to change the variable labels, the table is not shown and the screen greys out. This does not happen for other files, so I suppose the NA/missing value is the problem here. The WEIGHT variable is the last variable in the file. 

I wonder whether this has to do with the way the label information is put into a df in line 698 in server.R. 

This is a file-specific issue but would be nice if it can be solved, since more files may contain some missing labels

**Comment by bernhard-da** [comment]
as you pointed out, this seems to be a problem with the input data. I would strongly suggest to fix the input data in this case. What happens if you do not set them to `NA` but to a character (eg. `""`)? If this helps, I'll merge the pull request.

**Comment by mwelch750** [comment]
I agree that in an ideal world the input data should be fixed. The problem though is that the user does not really get an idea that there is a problem with the input data or which variable - they just get a grey screen. If the "" works then that would be a better solution.

**Comment by thijsbenschop** [comment]
Hi,

Unfortunately an empty string doesn't work. See also the different commits
I tried in the pull requests (NA, "", " " and "no label".

**Comment by bernhard-da** [comment]
after some checkings, I am pretty sure that it has nothing to do with missing labels but with non-valid encoded meta information. Please check the variable labels for H31 and H45 in which the character-sequence (`\x85`) occurs. perhaps we could make an additional checks using `validUTF8()` in `readMicrodata()` to prevent things like this.

**Comment by thijsbenschop** [comment]
Thanks for checking. I added a few lines to extractLabels and readMicrodata to check the labels. I also uploaded a new file with corrected labels. The commits are in pull request #177.

It seems that both caused troubles, the missing label and the corrupted labels. Therefore, I would suggest to keep the code replacing NULL with NA.

**Comment by thijsbenschop** [comment]
PS: It took me a while to find out how to generate an error message. I hope it is correct how I did it. Unfortunately this resulted in many commits.

**Comment by bernhard-da** [comment]
thx. the pull-request is merged.
