### ISSUE TITLE
Issue with microaggregation in sdcApp

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#181]
Hi,

I tested the following:
- load testdata
- convert roof to factor
- set up sdc problem with cat-roof and cont -expend, income, savings
- apply microaggregation, (mdav, aggr =5) on al three simultaneously

I get the following reproducible warning in the console:
```
Listening on http://127.0.0.1:3613
Warning: Error in eval: object 'NA's' not found
Stack trace (innermost first):
    84: eval
    83: eval
    82: [.data.table
    81: [ [controllers/ui_setup_sdc.R#199]
    80: renderUI [controllers/ui_setup_sdc.R#199]
    79: func
    78: origRenderFunc
    77: output$show_info_comp_numvars
     2: shiny::runApp
     1: sdcApp
```

This is the script:
```
require(sdcMicro)
inputdata <- readMicrodata(path="testdata", type="rdf", convertCharToFac=FALSE, drop_all_missings=FALSE)
inputdataB <- inputdata

## Set up sdcMicro object
sdcObj <- createSdcObj(dat=inputdata,
                       keyVars=c("roof"),
                       numVars=c("expend","income","savings"),
                       weightVar=NULL,
                       hhId=NULL,
                       strataVar=NULL,
                       pramVars=NULL,
                       excludeVars=NULL,
                       seed=0,
                       randomizeRecords=FALSE,
                       alpha=c(1))

## Microaggregation
sdcObj <- microaggregation(obj=sdcObj, variables=c("expend","income","savings"), aggr=5, method="mdav")
```
The warning is also shown on the summary page:
![image](https://cloud.githubusercontent.com/assets/8253935/23303289/7164f4b4-fa93-11e6-90d5-28db4aef013d.png)

I don't get the error in the R console.

What could be the reason for this warning/error?

I also noticed that in the box to select the variables for microaggregation, unlike in other similar boxes, I cannot select several variables at once. After each selection I have to re-click in the box to show the drop-down menu again.

**Comment by bernhard-da** [comment]
thx for reporting. issue is fixed.

**Comment by thijsbenschop** [comment]
Thanks!
