### ISSUE TITLE
Enhancement: Tabulation of pram variables in sdcApp

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#182]
Hi,

I noticed that in the risk and utility tab I can only compare the tabulations before and after of the selected categorical key variables. Would it be possible to add the pram variables here too? This would allow to see the effect of invariant pram on multivariate tabulations.

Thanks!

**Comment by bernhard-da** [comment]
I'll look into this.

**Comment by bernhard-da** [comment]
hi, please test and report back if this is what you were looking for. the plots should now also work for pram-variables.

**Comment by thijsbenschop** [comment]
Thanks, this is a valuable addition to the GUI. All works as expected. Thank you for your quick response.
