### ISSUE TITLE
Disable sdc problem button until all selections are valid

### ISSUE THREAD

**Issue by mwelch750** [sdcTools/sdcMicro#183]
Use testdata
Setup problem

Set urbrul to cat. error correctly states it is not a factor. 
Cancel message - but dont fix
Select electcon as cat.
Error regarding urbrur correctly comes back
Cancel message
I am still presented with a blue sdc setup button. It should not be allowed to continue as we
have a urbrur still set as cat. when it is type numeric.
Basically I can set up a numeric as categorical, by overriding the messages to prevent accidental selections.
sdc problem is setup
Solution: Disable the blue button until the problem is fixed.

**Comment by bernhard-da** [comment]
hi, thx for reporting. please check with the latest commit which should fix this issue.

**Comment by mwelch750** [comment]
Thanks for the quick response:
Good, that is what we had in mind. However ,after fixing the selection the button does not reappear.

**Comment by bernhard-da** [comment]
I can't reproduce this behaviour. When I fix all problems, the blue button reappears.

**Comment by thijsbenschop** [comment]
Thanks, same here. We were too quick and didn't scroll down all the way to see the button.

Thanks for the fix!
