### ISSUE TITLE
Infinite Loop in `localSuppressionWORK` (difference in `fk` for `freqCalc` and `cpp_calcSuppInds`)

### ISSUE THREAD

**Issue by vdorie** [sdcTools/sdcMicro#184]
The following scenario causes `kAnon` to hang:

    mat <- matrix(c(
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 6, 6, 6, 4, 3, 6, 4, 4, 4, 4, 3, 2,
        3, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4, 5, 4, 4, 4, 4, 4, 6, 6, 4, 4, 4, 4, 4, 3,
        6, 6, 4, 2, 2, 2, 2, 6, 4, 4, 4, 4, 6, 4, 5, 5, 4, 5, 4, 4, 4, 4, 6, 4, 1, 2,
        2, 2, 2, 2, 2, 2, 4, 6, 6, 5, 6, 3, 4, 5, 6, 4, 6, 5, 4, 4, 4, 3, 3, 6, 5, 2,
        2, 4, 2, 6, 5, 3, 4, 6, 4, 5, 6, 2, 5, 3, 4, 4, 4, 5, 4, 4, 4, 6, 4, 5, 2, 2,
        4, 3, 4, 6, 6, 6, 4, 4, 5, 6, 6, 4, 4, 4, 5, 4, 5, 4, 2, 2, 2, 5, 4, 4, 5, 6,
        3, 4, 4, 3, 4, 4, 5, 5, 3, 6, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 5, 4, 4, 4, 6, 4,
        3, 3, 5, 5, 6, 4, 6, 4, 4, 3, 5, 6, 4, 5, 4, 6, 3, 6, 2, 2, 2, 2, 2, 5, 5, 5,
        5, 4, 6, 4, 3, 4, 6, 6, 4, 4, 3, 4, 4, 4, 4, 4, 2, 2, 5, 4, 2, 2, 2, 4, 4, 5,
        6, 6, 3, 4, 4, 4, 4, 4, 6, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 4, 3, 6, 4, 4, 4, 5,
        4, 6, 6, 4, 4, 3, 4, 4, 4, 4, 3, 6, 4, 6, 4, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        6, 6, 6, 6, 6, 6, 6, 6, 2, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        1, 4, 6, 6, 4, 6, 6, 6, 6, 4, 6, 6, 6, 6, 1, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 4, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 4, 6, 6, 6, 6,
        2, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 6, 1, 6, 6, 6, 6, 6, 2, 6, 6, 6, 6, 2, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 4, 4, 6, 6, 6, 4, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 4, 4,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6),
      ncol = 3,
      dimnames = list(NULL, c("gender", "age_group", "race")))
    
    require(sdcMicro)
    sdc <- createSdcObj(mat, keyVars = c("gender", "age_group", "race"))
    sup <- kAnon(sdc, k = 5, importance = c(3L, 2L, 1L))

An analysis of `localSuppressionWORK` shows that this occurs due to a difference in how `freqCalc` and `cpp_calcSuppInds` determine `fk` in the presence of `NA` values. Specifically, after a few iterations and for a problem row of:

    gender age_group      race 
         1         6         6

`cpp_calcSuppInds ` determines an `fk` of 5, which in turn causes `res$fk >= k` to evaluate to `TRUE` and the loop to break. However, `freqCalc` shows a `k` of 4 for this index, so that the `while` loop continues with no modification to `x`. The relevant contents of the local variable `mat` at this time are:

         gender age_group race
    [1,]     NA         6    6
    [2,]      1         6    6
    [3,]      1         6    6
    [4,]     NA        NA   NA
    [5,]      1         6    6

The difference is due to a row ending up completely suppressed by the algorithm, i.e. all three key variables set to `NA`. Changing a single `NA` in that row to match the problem index (e.g., setting `gender` equal to 1 in row 4 above) increases the result of `freqCalc` while leaving `cpp_calcSuppInds` unchanged.

The issue can be examined directly by modifying the `while(runInd)` loop to first cache an `x.old <- x` and, before repeating, checking `if (all(!is.na(x) | is.na(x.old))) browser()`.

**Comment by bernhard-da** [comment]
hi @vdorie 

thx for reporting and this very helpful bugreport. i just pushed an update to the next-branch and I would be happy to hear from you if the issue is fixed.

**Comment by vdorie** [comment]
That has solved the issue, thank you.
