### ISSUE TITLE
Local Suppression result fails with more than one strata

### ISSUE THREAD

**Issue by vdorie** [sdcTools/sdcMicro#185]
When using `kAnon` with more than one strata variable, I get the error:

    Error in x[[i]] <- value : 
      more elements supplied than there are to replace

Example:

    require(sdcMicro)
    
    mat <- matrix(sample(3, 3 * 8, replace = TRUE),
                  ncol = 3,
                  dimnames = list(NULL, c("gender", "age_group", "race")))
    mat <- cbind(mat,
                 s1 = rep(c(1, 2), 4),
                 s2 = rep(c(1, 2), c(4, 4)))
    
    sdc <- createSdcObj(mat,
                        keyVars = c("gender", "age_group", "race"),
                        strataVar = c("s1", "s2"))
    sup <- kAnon(sdc, k = 5, importance = c(3L, 2L, 1L))

This occurs on line 464 of localSuppression.R:

    NAinKey[[strataVars]] <- NULL

I believe that this should be changed to:

    NAinKey[,strataVars] <- NULL

**Comment by bernhard-da** [comment]
hi @vdorie, thx for reporting. i just pushed an update which should fix the issue. please test if it really does :)

**Comment by bernhard-da** [comment]
hi @vdorie , can you confirm that the issue is fixed?

**Comment by vdorie** [comment]
Yes, it is fixed.
