### ISSUE TITLE
Default order of importance for local suppression in GUI

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#187]
Hi,

in the help of the local suppression function is stated that: "If not specified, the importance vector is instructed in a way such that key variables with a high number of characteristics are considered less important than key variables with a low number of characteristics."

I assume that this is ensured in lines 343-345 of localSuppression.R:
```
if (is.null(importance)) {
    xx <- x[,lapply(.SD, function(y) { length(table(y))}), .SDcols=keyVars]
importance <- match(names(xx), names(sort(xx, decreasing=FALSE)))
```

Looking at what happens in the GUI if no importance vector is specified, I noticed in server.R in lines 306-307 that they are set 1 to n, so taking the order the variables appear in the dataset (I assume that get_keyVars gets the key variables in the order they appear in the dataset). 

```
    if (kAnon_useImportance()) {
      cur_importance <- kAnon_impvec()
    } else {
      # default: 1:n
      cur_importance <- 1:length(get_keyVars())
}
cmd <- paste0(cmd,", importance=",VecToRStr(cur_importance, quoted=FALSE))
```
If this is the case, the localSuppression algorithm is used with an importance vector that doesn't make much sense and the default option of ordering according to the number of levels is overwritten.

Could you please confirm whether this is the case? If so, we should either change server.R in such a way that importance is NULL (line 307)
```
cur_importance <- NULL
```
or change the lines to
```
    if (kAnon_useImportance()) {
      cur_importance <- kAnon_impvec()
      cmd <- paste0(cmd,", importance=",VecToRStr(cur_importance, quoted=FALSE))
    } else {
      # default: NULL
      cmd <- paste0(cmd,", importance=NULL")
}
```
or set the vector to the order of key variables according to the number of levels.

**Comment by bernhard-da** [comment]
thx for reporting. the issue should now be fixed. please test and report back.

**Comment by thijsbenschop** [comment]
I think pull request #188 fixes the order of importance as specified in the anonymization steps overview
