### ISSUE TITLE
Select hhid for randomization

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#190]
In line 399 of auxfuntions.R hhid is set to NULL. hhid in line 432 of auxfuntions.R is not initialized and should be initialized in line 427 of auxfuntions.R.
This leads to errors in case randomizeRecords is "byHH" or "withinHH" both when used in command line as well as in the GUI.
Pull request #189 solves should solve this issue.

**Comment by bernhard-da** [comment]
thx for spotting and fixing. already merged the request.
