### ISSUE TITLE
Question on risk measure for numeric variables in GUI sidebar

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#192]
Hi,

I was looking into the numerical risk measures in the sidebar in the GUI and noticed that in the following overview (note that I changed the title from "Numeric Risk") only the value modified, risk_min can change. 

![image](https://cloud.githubusercontent.com/assets/8253935/24902626/0987b480-1eab-11e7-8a12-ac462dadc16c.png)

This is specified in line 80 in ui_sidebar_info.R:
```
 dt <- data.table(data=c("original","modified"), risk_min=paste0(c("100.00",x$risk_up),"%"), risk_max=paste0(c("100.00","100.00"),"%"))
```
If I compare this to lines 28 and 29 in ui_risk_numerical.R, there are a few differences.
```
column(12, p("The disclosure risk in the anonymized dataset is currently between",code("0%"),"and",code(paste0(x$risk_up,"%")),"."), align="center"),
column(12, p("In the original data the risk is assumed to be between",code("0%"),"and",code("100%"),"."), align="center"))
```

Therefore, I wonder whether I correctly interpret the risk measure by assuming that line 80 in ui_sidebar_info.R should be:
```
 dt <- data.table(data=c("original","modified"), risk_min=paste0(c("0.00","0.00"),"%"), risk_max=paste0(c("100.00",x$risk_up),"%"))
```
In that case the overview would look like:
![image](https://cloud.githubusercontent.com/assets/8253935/24903032/6cbfd4a0-1eac-11e7-8d72-fb68ce5fb09c.png)

and the value modified, risk_max can change.

**Comment by thijsbenschop** [comment]
If so, I added this change to pull request #191

**Comment by bernhard-da** [comment]
yep, that's the way it should be. 0-100% in original data, 0-upper risk estimate in modified data. i'll merge the pull-request in a second. thx for updating this
