### ISSUE TITLE
sdcApp - SAS available for upload but not for export

### ISSUE THREAD

**Issue by cmachingauta** [sdcTools/sdcMicro#194]
Hi,
Why is it that we can load SAS data, but there is no option to export back to SAS after anonymization? 
![image](https://cloud.githubusercontent.com/assets/7582929/25012482/a13c3280-203e-11e7-8637-0a09cbdc267a.png)

![image](https://cloud.githubusercontent.com/assets/7582929/25012484/a40d3338-203e-11e7-8f60-49d03d0aa369.png)

**Comment by bernhard-da** [comment]
sas export was not possible because in pkg `haven`, a `write_sas()` function appeared in a quite recent version. please check the update and report back. it should fix the issue.

**Comment by cmachingauta** [comment]
I see the export to SAS option now.
Thank you for the prompt response!
