### ISSUE TITLE
'Risky observations' table shows original values even after the values have been recoded 

### ISSUE THREAD

**Issue by cmachingauta** [sdcTools/sdcMicro#198]
When I recode values in a variable and then go to the Risky observations table, How come I still see the original values when I just recoded it?
Try loading the test data in sdcApp and set up an sdc problem by selecting key variables e.g. relat, age, hhcivil and set sampling weight as the weight var.
Recode relat categories 4+ to other 
Now go to the risk/utility window to view the risky observations after making this modification. Why is it that I still see observations with values >4 for the relat variable even after I recoded them? 
![image](https://cloud.githubusercontent.com/assets/7582929/25495227/6e19a844-2b4a-11e7-9e36-d97f9e76895c.png)

**Comment by bernhard-da** [comment]
Hi @cmachingauta, thx for reporting. Indeed, the original (unmodified) key variables were displayed in this table. I just pushed a fix. Please have a look and report back, if the issue has been fixed.

**Comment by cmachingauta** [comment]
Thanks, fixed now
![image](https://cloud.githubusercontent.com/assets/7582929/25497932/20014338-2b54-11e7-9766-9b7896650801.png)
