### ISSUE TITLE
pram | pram_strata | localSuppression  

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/sdcMicro#2]
problem: es koennen keine "nicht-keyVars" als variablen fuer pram verwendet werden. gleichzeitig ist es nicht möglich, localSuppression() nur auf ein subset von "keyVars" auszuführen. Ich denke, folgendes sollte möglich sein:
- data(free1)
- sdc <- createSdcObj(free1, keyVars=c("REGION","SEX","AGE","MARSTAT","KINDPERS"),weightVar="WEIGHT")
- sdc <- localSuppression(sdc, vars=c("REGION","SEX","AGE", k=3)
- sdc <- pram(sdc, vars=c("MARSTAT","KINDPERS")
- sdc <- pram(sdc, vars=c("EDUC1")

zum programmieren in sdcMicro scheint es recht einfach zu sein, aber ich bin mir nicht sicher, ob das nicht auswirkungen auf das gui und andere sachen (extractManipData(), get.sdcMicroObj(..., type="manipData")) hat. alex?

**Comment by matthias-da** [comment]
ja, scheiBe. Das waere naemlich das was wir wollen (macht eh keinen Sinn
k-anoymity und das ganze Zeugs bei gepramten Vars....

LG
Matthias

**Comment by alexkowa** [comment]
Naja so leicht ist das nicht zu integrieren, weil die Philosophie ja ich in manipKeyVars bzw. manipNumVars sind die geänderten Daten und in origData die original Daten, natürlich könnte ich für pram auf die Variable aus origData zugreifen, dass machen wir ja auch z.b. bei den Distanzvariablen für microaggregation. Die Frage ist nur wo wir die geprammte Variable abspeichern in einem neuen Slot "manipSensVars" oder so?? das müsste man dann überall miteinbauen?!

**Comment by matthias-da** [comment]
manipPramVars waere schoen und localSuppression sollte auf subsets anwendbar sein.
- fuer den Report muss man dann auf manipPramVars zugreifen. 
- ein Vergleich Kategorien origData und manipPramVars ist einfach
- im GUI koennte man sich ueberlegen auch diesen Vergleich klickbar zu machen.

Alternativer (besserer?) Ansatz: eine Implementierung die das erlaubt:
sdc <- createSdcObj(free1, keyVars=c("REGION","SEX","AGE"), pramVars=c("MARSTAT", "KINDPERS") weightVar="WEIGHT")
sdc <- localSuppression(sdc, k=3)
sdc <- pram(sdc)

**Comment by bernhard-da** [comment]
ja, das problem ist wirklich, dass es sich "durchzieht". ich meine man koennte ja auch einen indexvector/liste einfuehren, der indiziert, was mit welchen variablen in manipKeyVars gemacht wurde.

also wenn ich 5 key-vars habe (a,b,c,d,e) und ich moechte auf a,b,c localSuppression() und auf d,e pram anwenden, haette ich zum schluss soetwas wie:
obj@statusKeyVars:  c("localSuppression", "localSuppression","localSuppression,"pram","pram")

mit dem man dann weitermachen kann. ich weiß, das ist auch keine optimale loesung aber irgendwas sollten wir uns da einfallen lassen.

**Comment by bernhard-da** [comment]
ps: gerade gesehen, der vorschlag von matthias klingt besser!

**Comment by alexkowa** [comment]
Ja, dann setzen wir Matthias Vorschlag um, werde morgen weitermachen am sdcMicro (mit Bernhard) und anschließend bauen wir es ins GUI ein

**Comment by matthias-da** [comment]
super - danke!

2013/10/6 alexkowa notifications@github.com

> Ja, dann setzen wir Matthias Vorschlag um, werde morgen weitermachen am
> sdcMicro (mit Bernhard) und anschließend bauen wir es ins GUI ein
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alexkowa/sdcMicro/issues/2#issuecomment-25767658
> .

## 

Matthias Templ

Statistics @ Vienna University of Technology
Methods @ Statistics Austria

Geoinformatics @ Palacky University Olomouc

Consulting @ data-analysis OG

Wiedner Hauptstr. 7, 1040 Vienna, Austria

http://www.statistik.tuwien.ac.at/public/templ

visit: http://www.data-analysis.at

visit: http://www.codawork2013.com

visit: http://rsummer.data-analysis.at
