### ISSUE TITLE
Including file name in sdc report

### ISSUE THREAD

**Issue by cmachingauta** [sdcTools/sdcMicro#209]
Hi,
Is it possible to include the file name (name of the input data) in the sdc report? 
This would be helpful when handling multiple files. Thanks
![image](https://cloud.githubusercontent.com/assets/7582929/26454966/a7a8e3b6-4136-11e7-98ce-c7a00c11a188.png)

**Comment by bernhard-da** [comment]
I'll have to look into it how we can preserve file-names after they've been uploaded to the system.

**Comment by bernhard-da** [comment]
hi @cmachingauta, can you test if everything works as expected so that I can close this issue?

**Comment by cmachingauta** [comment]
Thank you Berhnard, I tested and it works. Apologies for my late response, I was caught up with other work.
