### ISSUE TITLE
left menu is lost in microdata view if string UTF8 conversions take place.

### ISSUE THREAD

**Issue by mwelch750** [sdcTools/sdcMicro#214]
![image](https://user-images.githubusercontent.com/7872305/26877286-6cecd158-4b57-11e7-8980-0e079494ff30.png)

The page displaying a summary if UTF8 conversions should allow the user to clear the message and restore the left menu options - especially if the user is still allowed to continue to anonymize.

**Comment by thijsbenschop** [comment]
Hi, I think I did this on purpose, since the user has to decide how to solve this problem before continuing. Not showing the sidebar forces the user to take an action by preventing the user to navigate away without taking action. We can add the sidebar here of course.

See also the screenshots in pull request #199

**Comment by mwelch750** [comment]
As it stands now , the user can still navigate away and continue with process . If we don't want them to ,then further action should be prevented and the user should be told to start again. Otherwise we should enable the menu

**Comment by bernhard-da** [comment]
@thijsbenschop as this is your "baby", could you provide a patch to fix this? thx.

**Comment by thijsbenschop** [comment]
Yes, I can provide a patch. In which direction do we want to go: completely enable or show the menu?

**Comment by bernhard-da** [comment]
I'd prefer to show the left navigation bar and probably add some (additional) description or help-text (icon?) in the main view...

**Comment by thijsbenschop** [comment]
Ok, will do that

**Comment by bernhard-da** [comment]
@thijsbenschop any progress on this?

**Comment by thijsbenschop** [comment]
@bernhard-da, sorry, I forgot to do this. 

Which sidebar should we have there: the import_data sidebar or the modify_data sidebar. The former would make more sense if the default in that case is to reset the dataset (left button), the latter makes sense if the default is then to accept the changes (right button).
![schermafbeelding 2017-08-23 om 13 04 00](https://user-images.githubusercontent.com/8253935/29612931-f695c534-8803-11e7-8fe6-c5445512638d.png)
![schermafbeelding 2017-08-23 om 13 00 02](https://user-images.githubusercontent.com/8253935/29612932-f6b0d09a-8803-11e7-8aba-86b1a14dae33.png)

**Comment by bernhard-da** [comment]
@thijsbenschop good question, I'd to show the import_data sidebar because the import is not yet "finished" in a way. once the user accepts, the sidebar should change to the modify_data sidebar.

**Comment by thijsbenschop** [comment]
@bernhard-da, agreed, that would mean that clicking on any of the menu items in the left sidebar should trigger a delete as well. In some way this is counterintuitive, as the user could navigate to another page in the top navigation bar and use the data as is. Therefore, I was initially for not showing a sidebar and enabling the user to do anything but clicking these two buttons.

**Comment by thijsbenschop** [comment]
@bernhard-da, how about a sidebar with only one button to reset the data?

**Comment by bernhard-da** [comment]
would also be ok. we then have 2 times the reset button, but I think that's fine.

**Comment by mwelch750** [comment]
I think the side bar with the single option to reset the data is what we need here.

**Comment by thijsbenschop** [comment]
@bernhard-da, I just created a pull request with the sidebar (#230). The button to reset the data in the sidebar doesn't work. I'm using btn_reset_inputdata_xx, just as I did for the button in the main part. Could you please help me and explain what I did wrong here?

**Comment by bernhard-da** [comment]
@thijsbenschop do you have a test-dataset with some "wrong" encodings? 

as for the button, I guess the reason is, that the id must be unique (e.g try `btn_reset_inputdata_yy`) and add a corresponding event (`observeEvent(input$btn_reset_inputdata_yy, { ...})`) in `server.R` (line 1006ff).

**Comment by thijsbenschop** [comment]
@bernhard-da, the file HND_2012_L2L.dta in the shared Box folder 'sdcGUI() - comments/Data/Honduras testdata can be used for testing. Matthew sent you the link to this folder a while ago. Please let me know in case you cannot access the data there.

Thanks for your suggestion. I tried it, but this doesn't solve it. Also, this event is already used in ui_mofiy_data.R lines 877 ff., so I guess the uniqueness shouldn't play a role here (or is at least not the only problem). Do you have any other ideas? I will search in the meantime as well.

```
output$ui_modify_data_sidebar_left <- renderUI({
  output$btn_reset_inputdata <- renderUI({
    if (is.null(inputdata())) {
      return(NULL)
    }
    btn <- bsButton("btn_reset_inputdata_xx",label=("Reset inputdata"), block=TRUE, style="warning")
    fluidRow(
      #column(12, h4("Reset the inputdata"), align="center"),
      column(12, btn)
    )
  })
```

**Comment by bernhard-da** [comment]
I can't reproduce the utf-8 issue at all with `HND_2012_L2L.dta` but I made a commit (https://github.com/thijsbenschop/sdcMicro/commit/bbee9dbaa05583e6355b13c595108be0c805cfbb) to your repo relevant for the pull request. could you check if it works? if not, please revert the commit.

**Comment by thijsbenschop** [comment]
@bernhard-da, thanks for your help. Your approach works, but the modal window disappeared immediately without clicking as both events (modal window and reset event ) had the same ID. I changed the name of one event in commit https://github.com/thijsbenschop/sdcMicro/commit/57a1cc4420d20d524548912592e5594afcd9cd37 and now it works as it should. I think this solves this issue.
