### ISSUE TITLE
 plot.sdcMicroObj doesn't like long column names

### ISSUE THREAD

**Issue by bebru** [sdcTools/sdcMicro#224]
If a column name of the used dataset is 12 characters or more, `plot.sdcMicroObj` returns an error.

```r
library(sdcMicro)
data(testdata)

names(testdata)[names(testdata)=="urbrur"] <- "abcdefghijkl"
sdc <- createSdcObj(testdata,
                    keyVars=c('abcdefghijkl','roof','walls','water','electcon','relat','sex'),
                    numVars=c('expend','income','savings'), w='sampling_weight')
sdc <- localSuppression(sdc)
plot(sdc)
```

**Comment by bernhard-da** [comment]
hi @bebru, the function actually returns a warning (`Too long variable names are cutted!`) and not an error. the plot is produced as expected.

**Comment by bebru** [comment]
Hi @bernhard-da , sounds good, but didn't act like that neither with CRAN nor branch next version.
![bildschirmfoto vom 2017-06-28 13-53-45](https://user-images.githubusercontent.com/12512888/27636059-fac90768-5c09-11e7-89e2-20471ffb7ca5.jpg)

**Comment by bernhard-da** [comment]
hi, thx for the feedback. i was now able to reproduce this issue and will fix it.

**Comment by bernhard-da** [comment]
hi @bebru, could you please check if the issue is fixed?

**Comment by bebru** [comment]
Yes, works as described now (returns a warning). Thanks!
