### ISSUE TITLE
dUtility() - missing set of parentheses?

### ISSUE THREAD

**Issue by echan5** [sdcTools/sdcMicro#231]
Hi,

If the formula for dUtility(method="IL1") is based on the formula shown for IL1s on page 19 of [https://cran.r-project.org/web/packages/sdcMicro/vignettes/sdc_guidelines.pdf](https://cran.r-project.org/web/packages/sdcMicro/vignettes/sdc_guidelines.pdf), I believe line 90 of dUtility.R is missing a set of parentheses, resulting in sqrt(2) being multiplied instead of divided.

Currently:
`a[[i]] <- abs((x[[i]] - xm[[i]])/sd(x[[i]], na.rm = TRUE) * sqrt(2))`

Fix (I believe):
`a[[i]] <- abs((x[[i]] - xm[[i]])/(sd(x[[i]], na.rm = TRUE) * sqrt(2)))`

Secondly, if the data utility function is computing an information loss metric, does it mean the lower the value returned by this data utility function, the higher the data utility (i.e. the lower the value, the "better") - am I interpreting correctly? (Without having looked through the function code, I actually would have thought the higher the value the better based on the "data utility" name).

Thank you for any clarifications!

**Comment by bernhard-da** [comment]
hi @echan5 , thx for reporting. this was indeed a bug and will be fixed in the next cran-version.

as for your question: IL1 is a measure of information loss, so the higher this measure, the lower the data utility or the other way round. thus your interpretation was correct.
