### ISSUE TITLE
strata_variables not working in pram()

### ISSUE THREAD

**Issue by echan5** [sdcTools/sdcMicro#234]
Hi, I'm using the pram() function and hoping to apply it within strata. If I'm understanding the purpose of the strata_variables argument correctly (are values supposed to change to other values within their own strata only?), I don't believe it is working as expected. Here is some sample code:

`testdata = data.frame(category = c(rep("A",90), rep("B",90)), subcategory = c(rep(seq(1,3,1),30), rep(seq(4,6,1),30)))`
`testdata$category = as.factor(testdata$category)`
`testdata$subcategory = as.factor(testdata$subcategory)`
`table(testdata)`
`res = pram(testdata, variables="subcategory", strata_variables="category")`
`summary(res)`
`table(res[c("category","subcategory_pram")])`

If it's supposed to convert to other values within strata only, then values of subcategory for category A should only ever be 1, 2, or 3, while values of subcategory for category B should only ever be 4, 5, or 6, but you'll see in the perturbed data that this is not the case.

Or please let me know if I've misunderstood. Thank you!

**Comment by bernhard-da** [comment]
hi @echan5, thx for reporting.

Indeed, applying `pram()` on different strata does not limit the (possible) changes to the values of the variable that only occur in the group but just applies a new random transition matrix (using the same parameters) in each subgroup. In this sense, the stratification-"feature" of this method is a bit misleading.

We might however add a parameter to restrict changes to the values that actually occur in future versions.
