### ISSUE TITLE
Mismatch in "Disclosure Risk (original data) for Categorical Variables" in report() when there are missing values and alpha is set

### ISSUE THREAD

**Issue by echan5** [sdcTools/sdcMicro#235]
Hi, I have a dataset with missing values and have alpha set to a non-default value in createSdcObj(). When this is the case, it seems that report() does not report the correct "Disclosure Risk for Categorical Variables" for the original data. I have some sample code below.

```
data(testdata2)

# add some missing values
testdata2[1:10,"urbrur"] = NA
testdata2[20:30,"roof"] = NA

# version with no alpha - original risk is 21.61%
sdc <- createSdcObj(testdata2, keyVars=c('urbrur','roof','walls','sex'))
sdc <- localSuppression(sdc)
print(sdc,"risk")
sdc@originalRisk$global$risk_pct
report(sdc, internal=TRUE)

# version with alpha - original risk is 27.98%, but report() reports 21.61%
sdc_alpha <- createSdcObj(testdata2, keyVars=c('urbrur','roof','walls','sex'), alpha=0)
sdc_alpha <- localSuppression(sdc_alpha)
print(sdc_alpha,"risk")
sdc_alpha@originalRisk$global$risk_pct
report(sdc_alpha, internal=TRUE, filename="alpha")
```

It seems it's just reporting the original risk as if the alpha argument was not applied. The modified data risk seems correct though.

Thank you

**Comment by bernhard-da** [comment]
hi @echan5 

thx for reporting this. can you please check after my latest commit, if the issue has been fixed? thx!

**Comment by echan5** [comment]
No, it returns a NULL (renders as "original data: % (~ observations)" in the html file). I just tried the sample code above. I think it should be `origRisk$global$risk_pct`, not `origRisk$global_risk_pct` in line 225 of report.R?

**Comment by bernhard-da** [comment]
hi, this was exactly the problem. should be fixed now!

**Comment by echan5** [comment]
Works now, thank you!

**Comment by bernhard-da** [comment]
@echan5 thx for testing!
