### ISSUE TITLE
Support for Shiny Server

### ISSUE THREAD

**Issue by prcleary** [sdcTools/sdcMicro#240]
I maintain Shiny Server on a VM within my organisation's network. I was asked to see if `sdcMicro` was compatible with this. As far as I can see the Shiny app is intended to run locally, but if possible running it on Shiny Server (within a local network) would be of value to some like me.

**Comment by alexkowa** [comment]
It is possible, you have to take the following steps:
 - Copy the directory `inst/shiny/sdcApp` to your shiny server
 - Add `library(sdcMicro)` at the beginning of the `global.R`
 - Add the code below right after the line with `library(data.table)`
```
### Beginning required code for deployment
.startdir <- .guitheme <- .guijsfile <- NULL
maxRequestSize <- 50
options(shiny.maxRequestSize=ceiling(maxRequestSize)*1024^2)

.GlobalEnv$.startdir <- getwd()

theme="IHSN"
.GlobalEnv$.guitheme <- "ihsn-root.css"
.GlobalEnv$.guijsfile <- "js/ihsn-style.js"
## End of deployment code
```
Is this working for you?

**Comment by alexkowa** [comment]
@bernhard-da maybe we can add it to the global.R in combination with a `match.call()` ?
See https://stackoverflow.com/questions/15595478/how-to-get-the-name-of-the-calling-function-inside-the-called-routine

**Comment by bernhard-da** [comment]
@alexkowa could work.

i have no shiny server running, but can you test this at the beginning of `global.R`?

```
if (sys.calls()[[1]]!="sdcApp()") {
  ### Beginning required code for deployment
  .startdir <- .guitheme <- .guijsfile <- NULL
  maxRequestSize <- 50
  options(shiny.maxRequestSize=ceiling(maxRequestSize)*1024^2)

  .GlobalEnv$.startdir <- getwd()

  theme="IHSN"
  .GlobalEnv$.guitheme <- "ihsn-root.css"
  .GlobalEnv$.guijsfile <- "js/ihsn-style.js"
  ## End of deployment code
}
```

**Comment by alexkowa** [comment]
Yes, this works and I committed it.

**Comment by prcleary** [comment]
Works for me too - thanks, much appreciated.
