### ISSUE TITLE
Sort table of risky observations on column indivRisk doesn't work properly

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#241]
The column indivRisk is transformed into a string with the risk values by using formatC in line 57 of ui_results_categorical. When the format "fg"is used, at least three **significant** digits are used. This can lead to strings of different length, and strings are first sorted by number of characters and then by the actual values. This leads e.g. to: "1" < "0.5" < "0.73" < "0.123" and messes up the order of the numeric values.

 A solution would be to use format "f" and set digits to 5 or 6.
```
if (nrow(df)>0) {
   df$indivRisk <- formatC(df$indivRisk, format="f", digits=6)
}
```
![capture1234](https://user-images.githubusercontent.com/8253935/33942052-07b6ec9e-e015-11e7-9ba9-25b870c3f202.PNG)

Alternatively, the values could be simply rounded to 5/6 digits and kept in numeric format. That also gets the values right-aligned, which even looks nicer.
```
if (nrow(df)>0) {
  df$indivRisk <- round(df$indivRisk, digits = 6)
}
```
![capture1222](https://user-images.githubusercontent.com/8253935/33942206-73388f22-e015-11e7-9cdf-5a9e86de3dac.PNG)

**Comment by bernhard-da** [comment]
hi @thijsbenschop, i like the first proposed solution(workaround) better. just pushed it.
