### ISSUE TITLE
Inaccurate description of risk measurs in GUI

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#242]
On the page risk measure page, the description of the displayed risk measures isn't accurate in one case:
![capture111](https://user-images.githubusercontent.com/8253935/33943184-a87b3e5c-e018-11e7-94f7-4b5f34caa50c.PNG)

The displayed risk measure is computed in lines 368 and 369 of reactive_expressions.R as:
```
  res$s <- sum((risk$individual[,1] > median(risk$individual[,1])+2*mad(risk$individual[,1])) & (risk$indiviual[,1] > bm))
  res$sorig <- sum((originalRisk$individual[,1] > median(originalRisk$individual[,1])+2*mad(originalRisk$individual[,1])) & (originalRisk$indiviual[,1] > bm))
```
bm is here set to 0.1.

So the description should be the same as on the summary page:
![capture11](https://user-images.githubusercontent.com/8253935/33943274-f109ed3a-e018-11e7-9f55-927d60b503af.PNG)

which is computed in lines 159 and 160 of printFunctions.r:

```
    s_mod <-sum((iR_mod > median(iR_mod) + 2*mad(iR_mod)) & (iR_mod>0.1))
    s_orig <- sum((iR_orig > median(iR_orig) + 2*mad(iR_orig)) & (iR_orig>0.1))
```
Besides this the values shuld be identical, but aren't as shown in the screenshots.

**Comment by thijsbenschop** [comment]
See pull request #243

**Comment by bernhard-da** [comment]
@thijsbenschop hi, thx for reporting. i just fixed this. the inconsistency was because of a typo
