### ISSUE TITLE
Package vignette problems

### ISSUE THREAD

**Issue by yihui** [sdcTools/sdcMicro#247]
1. The Rnw vignette still contains Sweave syntax: https://github.com/sdcTools/sdcMicro/blob/master/vignettes/sdc_guidelines.rnw I recommend you to run `knitr::Sweave2knitr()` on it.

2. The Rmd vignette's YAML frontmatter is incorrect (`---` is missing in the beginning): https://github.com/sdcTools/sdcMicro/blame/master/vignettes/sdcApp.Rmd

**Comment by bernhard-da** [comment]
hi @yihui thx for reporting this. the 2nd issue is already fixed in the next branch and for the first one I just pushed the required changes. thx.

**Comment by yihui** [comment]
👍
