### ISSUE TITLE
R forced to restart when loading data through sdcApp on x86_64-pc-linux-gnu

### ISSUE THREAD

**Issue by Edouard-Legoupil** [sdcTools/sdcMicro#251]
HI,

When loading data and trying to explore it, the browser freezes and R is forced to restart...
![image](https://user-images.githubusercontent.com/1789444/38544048-033960f6-3caf-11e8-8859-ac52635e8ab3.png)

My platform is **x86_64-pc-linux-gnu**

I tried the following errors to capture issue but nothing comes out..
```
library(sdcMicro)
options(shiny.reactlog=TRUE)
traceback(sdcApp(maxRequestSize = 1000))
```

Thanks,
Edouard

**Comment by bernhard-da** [comment]
hi @Edouard-Legoupil thx for reporting this.

can you post the output of `sessionInfo()` prior to calling `sdcApp()`?

**Comment by bernhard-da** [comment]
also, you could try to start the interface from pure pure R command-line (excluding Rstudio for debugging). Perhaps you get some hints what went wrong there. Because on a fully updated x86_64 (archlinux), i can't reproduce with the latest CRAN version.

**Comment by Edouard-Legoupil** [comment]
Same with command-line...

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.10

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3
> library(sdcMicro)
--------
This is sdcMicro v5.1.0.
For references, please have a look at citation('sdcMicro')
Note: since version 5.0.0, the graphical user-interface is a shiny-app that can be started with sdcApp().
Please submit suggestions and bugs at: https://github.com/sdcTools/sdcMicro/issues
--------
> sdcApp(maxRequestSize = 1000)
Loading required package: shiny

Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable

data.table 1.10.4.3
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes, videos and slides: http://r-datatable.com

Listening on http://127.0.0.1:3751

 *** caught segfault ***
address 0xb7, cause 'memory not mapped'

Traceback:
 1: .External("cairo_create_new_device", as.character(ctype), file,     width, height, pointsize, bg, canvas, umpl, dpi, ..., PACKAGE = "Cairo")
 2: Cairo(width, height, type = "png", file = filename, pointsize = pointsize,     bg = bg, res = res, ...)
 3: pngfun(filename = filename, width = width, height = height, res = res,     ...)
 4: (function (func, filename = tempfile(fileext = ".png"), width = 400,     height = 400, res = 72, ...) {    if (capabilities("aqua")) {        pngfun <- grDevices::png    }    else if ((getOption("shiny.usecairo") %OR% TRUE) && nchar(system.file(package = "Cairo"))) {        pngfun <- Cairo::CairoPNG    }    else {        pngfun <- grDevices::png    }    pngfun(filename = filename, width = width, height = height,         res = res, ...)    op <- graphics::par(mar = rep(0, 4))    tryCatch(graphics::plot.new(), finally = graphics::par(op))    dv <- grDevices::dev.cur()    on.exit(grDevices::dev.off(dv), add = TRUE)    func()    filename})(function () {    success <- FALSE    tryCatch({        grDevices::dev.control(displaylist = "enable")        result <- withVisible(func())        success <- TRUE    }, finally = {        if (!success) {            getDims()        }    })    if (result$visible) {        utils::capture.output({            plotResult <<- ..stacktraceon..(print(result$value))        })    }    recordedPlot <<- grDevices::recordPlot()    if (inherits(plotResult, "ggplot_build_gtable")) {        coordmap <<- getGgplotCoordmap(plotResult, pixelratio,             res)    }    else {        coordmap <<- getPrevPlotCoordmap(dims$width, dims$height)    }}, width = 1299L, height = 500L, res = 72)
 5: do.call(plotPNG, c(plotFunc, width = dims$width * pixelratio,     height = dims$height * pixelratio, res = res * pixelratio,     args))
 6: ..stacktraceoff..(do.call(plotPNG, c(plotFunc, width = dims$width *     pixelratio, height = dims$height * pixelratio, res = res *     pixelratio, args)))
 7: `<reactive:plotObj>`(...)
 8: ..stacktraceon..(`<reactive:plotObj>`(...))
 9: .func()
10: withVisible(.func())
11: withCallingHandlers({    .error <<- FALSE    withVisible(.func())}, error = function(cond) {    .value <<- cond    .error <<- TRUE    .visible <<- FALSE})
12: contextFunc()
13: env$runWith(self, func)
14: withReactiveDomain(.domain, {    env <- .getReactiveEnvironment()    .graphEnterContext(id)    on.exit(.graphExitContext(id), add = TRUE)    env$runWith(self, func)})
15: ctx$run(function() {    result <- withCallingHandlers({        .error <<- FALSE        withVisible(.func())    }, error = function(cond) {        .value <<- cond        .error <<- TRUE        .visible <<- FALSE    })    .value <<- result$value    .visible <<- result$visible})
16: self$.updateValue()
17: ..stacktraceoff..(self$.updateValue())
18: plotObj()
19: origRenderFunc(...)
20: `output$view_plot`(...)
21: ..stacktraceon..(`output$view_plot`(...))
22: orig(name = name, shinysession = self)
23: func()
24: withCallingHandlers(expr, error = function(e) {    if (is.null(attr(e, "stack.trace", exact = TRUE))) {        calls <- sys.calls()        attr(e, "stack.trace") <- calls        stop(e)    }})
25: captureStackTraces(expr)
26: withCallingHandlers(captureStackTraces(expr), error = function(e) {    if (inherits(e, "shiny.silent.error"))         return()    handle <- getOption("shiny.error")    if (is.function(handle))         handle()})
27: shinyCallingHandlers(func())
28: doTryCatch(return(expr), name, parentenv, handler)
29: tryCatchOne(expr, names, parentenv, handlers[[1L]])
30: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
31: doTryCatch(return(expr), name, parentenv, handler)
32: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
33: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
34: doTryCatch(return(expr), name, parentenv, handler)
35: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
36: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
37: doTryCatch(return(expr), name, parentenv, handler)
38: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
39: tryCatchList(expr, classes, parentenv, handlers)
40: tryCatch(shinyCallingHandlers(func()), shiny.custom.error = function(cond) {    if (isTRUE(getOption("show.error.messages")))         printError(cond)    structure(list(), class = "try-error", condition = cond)}, shiny.output.cancel = function(cond) {    structure(list(), class = "cancel-output")}, shiny.silent.error = function(cond) {    structure(list(), class = "try-error", condition = cond)}, error = function(cond) {    if (isTRUE(getOption("show.error.messages")))         printError(cond)    if (getOption("shiny.sanitize.errors", FALSE)) {        cond <- simpleError(paste("An error has occurred. Check your",             "logs or contact the app author for", "clarification."))    }    invisible(structure(list(), class = "try-error", condition = cond))}, finally = {    private$sendMessage(recalculating = list(name = name, status = "recalculated"))})
41: observerFunc()
42: doTryCatch(return(expr), name, parentenv, handler)
43: tryCatchOne(expr, names, parentenv, handlers[[1L]])
44: tryCatchList(expr, classes, parentenv, handlers)
45: tryCatch(if (..stacktraceon) ..stacktraceon..(observerFunc()) else observerFunc(),     shiny.silent.error = function(e) NULL)
46: contextFunc()
47: env$runWith(self, func)
48: withReactiveDomain(.domain, {    env <- .getReactiveEnvironment()    .graphEnterContext(id)    on.exit(.graphExitContext(id), add = TRUE)    env$runWith(self, func)})
49: ctx$run(.func)
50: run()
51: withCallingHandlers(expr, error = function(e) {    if (is.null(attr(e, "stack.trace", exact = TRUE))) {        calls <- sys.calls()        attr(e, "stack.trace") <- calls        stop(e)    }})
52: captureStackTraces(expr)
53: withCallingHandlers(captureStackTraces(expr), error = function(e) {    if (inherits(e, "shiny.silent.error"))         return()    handle <- getOption("shiny.error")    if (is.function(handle))         handle()})
54: shinyCallingHandlers(run())
55: doTryCatch(return(expr), name, parentenv, handler)
56: tryCatchOne(expr, names, parentenv, handlers[[1L]])
57: tryCatchList(expr, classes, parentenv, handlers)
58: tryCatch({    if (!.destroyed)         shinyCallingHandlers(run())}, error = function(e) {    printError(e)    if (!is.null(.domain)) {        .domain$unhandledError(e)    }})
59: flushCallback()
60: FUN(X[[i]], ...)
61: lapply(.flushCallbacks, function(flushCallback) {    flushCallback()})
62: ctx$executeFlushCallbacks()
63: .getReactiveEnvironment()$flush()
64: flushReact()
65: force(expr)
66: withRestoreContext(shinysession$restoreContext, {    msg$data <- applyInputHandlers(msg$data)    switch(msg$method, init = {        serverFunc <- withReactiveDomain(NULL, serverFuncSource())        if (!identicalFunctionBodies(serverFunc, appvars$server)) {            appvars$server <- serverFunc            if (!is.null(appvars$server)) {                attr(appvars$server, "shinyServerFunction") <- TRUE                registerDebugHook("server", appvars, "Server Function")            }        }        if (.globals$showcaseOverride && exists(".clientdata_url_search",             where = msg$data)) {            mode <- showcaseModeOfQuerystring(msg$data$.clientdata_url_search)            if (!is.null(mode)) shinysession$setShowcase(mode)        }        shinysession$manageInputs(msg$data)        if (!is.null(msg$data$.clientdata_singletons)) {            shinysession$singletons <- strsplit(msg$data$.clientdata_singletons,                 ",")[[1]]        }        local({            args <- argsForServerFunc(serverFunc, shinysession)            withReactiveDomain(shinysession, {                do.call(wrapFunctionLabel(appvars$server, "server",                   ..stacktraceon = TRUE), args)            })        })    }, update = {        shinysession$manageInputs(msg$data)    }, shinysession$dispatch(msg))    shinysession$manageHiddenOutputs()    if (exists(".shiny__stdout", globalenv()) && exists("HTTP_GUID",         ws$request)) {        shiny_stdout <- get(".shiny__stdout", globalenv())        writeLines(paste("_n_flushReact ", get("HTTP_GUID", ws$request),             " @ ", sprintf("%.3f", as.numeric(Sys.time())), sep = ""),             con = shiny_stdout)        flush(shiny_stdout)        flushReact()        writeLines(paste("_x_flushReact ", get("HTTP_GUID", ws$request),             " @ ", sprintf("%.3f", as.numeric(Sys.time())), sep = ""),             con = shiny_stdout)        flush(shiny_stdout)    }    else {        flushReact()    }    flushAllSessions()})
67: withReactiveDomain(shinysession, {    if (is.character(msg))         msg <- charToRaw(msg)    traceOption <- getOption("shiny.trace", FALSE)    if (isTRUE(traceOption) || traceOption == "recv") {        if (binary)             message("RECV ", "$$binary data$$")        else message("RECV ", rawToChar(msg))    }    if (isEmptyMessage(msg))         return()    msg <- decodeMessage(msg)    if (is.null(shinysession$restoreContext)) {        bookmarkStore <- getShinyOption("bookmarkStore", default = "disable")        if (bookmarkStore == "disable") {            shinysession$restoreContext <- RestoreContext$new()        }        else {            shinysession$restoreContext <- RestoreContext$new(msg$data$.clientdata_url_search)        }    }    withRestoreContext(shinysession$restoreContext, {        msg$data <- applyInputHandlers(msg$data)        switch(msg$method, init = {            serverFunc <- withReactiveDomain(NULL, serverFuncSource())            if (!identicalFunctionBodies(serverFunc, appvars$server)) {                appvars$server <- serverFunc                if (!is.null(appvars$server)) {                  attr(appvars$server, "shinyServerFunction") <- TRUE                  registerDebugHook("server", appvars, "Server Function")                }            }            if (.globals$showcaseOverride && exists(".clientdata_url_search",                 where = msg$data)) {                mode <- showcaseModeOfQuerystring(msg$data$.clientdata_url_search)                if (!is.null(mode)) shinysession$setShowcase(mode)            }            shinysession$manageInputs(msg$data)            if (!is.null(msg$data$.clientdata_singletons)) {                shinysession$singletons <- strsplit(msg$data$.clientdata_singletons,                   ",")[[1]]            }            local({                args <- argsForServerFunc(serverFunc, shinysession)                withReactiveDomain(shinysession, {                  do.call(wrapFunctionLabel(appvars$server, "server",                     ..stacktraceon = TRUE), args)                })            })        }, update = {            shinysession$manageInputs(msg$data)        }, shinysession$dispatch(msg))        shinysession$manageHiddenOutputs()        if (exists(".shiny__stdout", globalenv()) && exists("HTTP_GUID",             ws$request)) {            shiny_stdout <- get(".shiny__stdout", globalenv())            writeLines(paste("_n_flushReact ", get("HTTP_GUID",                 ws$request), " @ ", sprintf("%.3f", as.numeric(Sys.time())),                 sep = ""), con = shiny_stdout)            flush(shiny_stdout)            flushReact()            writeLines(paste("_x_flushReact ", get("HTTP_GUID",                 ws$request), " @ ", sprintf("%.3f", as.numeric(Sys.time())),                 sep = ""), con = shiny_stdout)            flush(shiny_stdout)        }        else {            flushReact()        }        flushAllSessions()    })})
68: messageHandler(binary, msg)
69: withCallingHandlers(expr, error = function(e) {    if (is.null(attr(e, "stack.trace", exact = TRUE))) {        calls <- sys.calls()        attr(e, "stack.trace") <- calls        stop(e)    }})
70: captureStackTraces(expr)
71: withCallingHandlers(captureStackTraces(expr), error = function(cond) {    if (inherits(cond, "shiny.silent.error"))         return()    if (isTRUE(getOption("show.error.messages"))) {        printError(cond, full = full, offset = offset)    }})
72: withLogErrors(messageHandler(binary, msg))
73: handler(binary, message)
74: doTryCatch(return(expr), name, parentenv, handler)
75: tryCatchOne(expr, names, parentenv, handlers[[1L]])
76: tryCatchList(expr, classes, parentenv, handlers)
77: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
78: try(handler(binary, message))
79: (function (handle, binary, message) {    for (handler in .wsconns[[as.character(handle)]]$.messageCallbacks) {        result <- try(handler(binary, message))        if (inherits(result, "try-error")) {            .wsconns[[as.character(handle)]]$close()            return()        }    }})("94243004480736", FALSE, "{\"method\":\"update\",\"data\":{\".clientdata_output_view_plot_width\":1299,\".clientdata_output_view_plot_height\":500,\".clientdata_output_ui_selvar1_hidden\":false,\".clientdata_output_ui_selvar2_hidden\":false,\".clientdata_output_view_plot_hidden\":false,\".clientdata_output_view_summary_hidden\":false}}")
80: evalq((function (handle, binary, message) {    for (handler in .wsconns[[as.character(handle)]]$.messageCallbacks) {        result <- try(handler(binary, message))        if (inherits(result, "try-error")) {            .wsconns[[as.character(handle)]]$close()            return()        }    }})("94243004480736", FALSE, "{\"method\":\"update\",\"data\":{\".clientdata_output_view_plot_width\":1299,\".clientdata_output_view_plot_height\":500,\".clientdata_output_ui_selvar1_hidden\":false,\".clientdata_output_ui_selvar2_hidden\":false,\".clientdata_output_view_plot_hidden\":false,\".clientdata_output_view_summary_hidden\":false}}"),     <environment>)
81: evalq((function (handle, binary, message) {    for (handler in .wsconns[[as.character(handle)]]$.messageCallbacks) {        result <- try(handler(binary, message))        if (inherits(result, "try-error")) {            .wsconns[[as.character(handle)]]$close()            return()        }    }})("94243004480736", FALSE, "{\"method\":\"update\",\"data\":{\".clientdata_output_view_plot_width\":1299,\".clientdata_output_view_plot_height\":500,\".clientdata_output_ui_selvar1_hidden\":false,\".clientdata_output_ui_selvar2_hidden\":false,\".clientdata_output_view_plot_hidden\":false,\".clientdata_output_view_summary_hidden\":false}}"),     <environment>)
82: doTryCatch(return(expr), name, parentenv, handler)
83: tryCatchOne(expr, names, parentenv, handlers[[1L]])
84: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
85: doTryCatch(return(expr), name, parentenv, handler)
86: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
87: tryCatchList(expr, classes, parentenv, handlers)
88: tryCatch(evalq((function (handle, binary, message) {    for (handler in .wsconns[[as.character(handle)]]$.messageCallbacks) {        result <- try(handler(binary, message))        if (inherits(result, "try-error")) {            .wsconns[[as.character(handle)]]$close()            return()        }    }})("94243004480736", FALSE, "{\"method\":\"update\",\"data\":{\".clientdata_output_view_plot_width\":1299,\".clientdata_output_view_plot_height\":500,\".clientdata_output_ui_selvar1_hidden\":false,\".clientdata_output_ui_selvar2_hidden\":false,\".clientdata_output_view_plot_hidden\":false,\".clientdata_output_view_summary_hidden\":false}}"),     <environment>), error = function (x) x, interrupt = function (x) x)
89: .Call("httpuv_run", PACKAGE = "httpuv", timeoutMillis)
90: run(timeoutMs)
91: service(timeout)
92: serviceApp()
93: withCallingHandlers(expr, error = function(e) {    if (is.null(attr(e, "stack.trace", exact = TRUE))) {        calls <- sys.calls()        attr(e, "stack.trace") <- calls        stop(e)    }})
94: captureStackTraces({    scheduleFlush()    while (!.globals$stopped) {        serviceApp()        Sys.sleep(0.001)    }})
95: ..stacktraceoff..(captureStackTraces({    scheduleFlush()    while (!.globals$stopped) {        serviceApp()        Sys.sleep(0.001)    }}))
96: shiny::runApp(appDir, display.mode = "normal", launch.browser = TRUE,     ...)
97: sdcApp(maxRequestSize = 1000)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:

**Comment by bernhard-da** [comment]
to me it seems as if there is a problem with either the Cairo package or the underlying cairo system(linux) libraries but not specifically with sdcMicro.

are all your packages up-to-date?

**Comment by Edouard-Legoupil** [comment]
Updating now..

**Comment by GregorDeCillia** [comment]
Another thing you can try is to disable cairo in with

    options(shiny.usecairo = FALSE)

**Comment by Edouard-Legoupil** [comment]
Working now with the Cairo option off! 

Thanks a lot!
