### ISSUE TITLE
maxRequestsize doesn't respond

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#252]
In commit 4aaf184577886c1a0695a081ce2837afec1f7fff, setting the maxRequestsize was put in a condition. It seems that this has effectively enabled maxRequestsize when not using a server. I cannot load larger datasets, even when setting the maxRequestsize before launching the app. If I install a previous version of the sdcMicro package, it works.

**Comment by thijsbenschop** [comment]
The command 

```
options(shiny.maxRequestSize=ceiling(maxRequestSize)*1024^2)
```

seems to be missing, so the shiny.maxRequestSize stays at its default (5MB?)

**Comment by bernhard-da** [comment]
@thijsbenschop thx. could you please try with current github version (which will shortly be cran 5.2.0)? i just tried and was able to upload a 20mb file without issues.

**Comment by bernhard-da** [comment]
@thijsbenschop thx for reporting. I just tried with latest version from github (which will soon be uploaded to cran) and changing `shiny.maxRequestSize` in `sdcApp()` does work. I just checked adding `print(options("shiny.maxRequestSize"))` to line 27 in `global.R` and started the app with a few different settings. i also was able to upload a 40mb file without problems (using the default parameters).

did you try with latest cran version or with the latest github version?

**Comment by thijsbenschop** [comment]
@bernhard-da , thanks for your quick response. Indeed, it works with 5.2.0, where 

```
if (!getShinyOption("sdcAppInvoked", FALSE)) {### Beginning required code for deployment
```

is used instead of 

```
if (sys.calls()[[1]]!="sdcApp()") {### Beginning required code for deployment
```
as in the current CRAN version (5.1.0). It also works with 5.0.4., where this wasn't added yet.

When will 5.2.0 be available from CRAN?

**Comment by bernhard-da** [comment]
soon :)

**Comment by GregorDeCillia** [comment]
Here is what happened with the old logic. If `sdcApp` was called with a parameter, let's say `sdcApp(100)`, then `sys.calls()[[1]]` returned the call `sdcApp(100)`, not `sdcApp()`. I just tried this with the following example. 

    f <- function(...){sys.calls()[[1]] == "f()"}
    f()
    ## [1] TRUE
    f(2)
    ## [1] FALSE

I suppose this should be mentioned as a bugfix in the `NEWS` prior to the next CRAN release.

**Comment by thijsbenschop** [comment]
Thanks for the explanation, @gregordecillia, that makes sense. So as soon the maxrequestsize was added, it won't trigger this part.
