### ISSUE TITLE
Add version for Stata export in GUI

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#255]
Hi,

the GUI can read Stata files created by Stata versions 8-14 with the read_dta function from the haven package. The write_dta function from the same package exports by default as a Stata 14 file. These files cannot be read by earlier Stata versions.

This means that users of earlier Stata versions can import files but can no longer open the exported files in Stata. Also, some specific software packages work only with Stata 12 or 13 files, as they weren't updated since the release of Stata 14 (an example is AdePT, see http://web.worldbank.org/archive/website01411/WEB/0__CON-3.HTM).

The write_dta function has an option to specify the Stata version. I would like to propose to add the selection of the version to the GUI.

**Comment by thijsbenschop** [comment]
This could look like this:
![schermafbeelding 2018-04-25 om 13 39 10](https://user-images.githubusercontent.com/8253935/39243600-4539ce10-488e-11e8-8985-a6e8fb2c7ca0.png)

**Comment by thijsbenschop** [comment]
PS: is your master branch the same as the version on CRAN and the next branch your development branch as it used to be in the past? I submitted the pull request to the master branch. Should I rather submit it to the next branch?

**Comment by bernhard-da** [comment]
hi. please create pull request against master branch.

**Comment by thijsbenschop** [comment]
Thanks, I have created the pull request to the master branch and updated the vignette in a new commit
