### ISSUE TITLE
Question: Large datasets

### ISSUE THREAD

**Issue by rebecabarros** [sdcTools/sdcMicro#265]
Hi all,

I'm trying to use sdcMicro with large datasets. Is there any sort of benchmark results about using the package with large datasets? Or any information about recommended configurations to run this kind of scenario?

I'm using sparklyr but seems like **createSdcObj** needs to collect the dataframe so data will be load into
server memory which leads to "out of memory" errors.

**Comment by bernhard-da** [comment]
hi @rebecabarros 

you're right. currently data needs to be kept in memory. any improvements/pull requests to change/improve this behaviour are very welcome but for now we do not intend to make changes in this area.

also, i am not aware of any (published) benchmarks.
