### ISSUE TITLE
Microaggregation  / MDAV / median

### ISSUE THREAD

**Issue by superjeje** [sdcTools/sdcMicro#266]
Hello

when trying to microaggregate using the MDAV method and the median as measure, I get the mean of the numVars instead of the median..

Is it a bug or where do i get wrong?

the version is : 5.3.0
executed on Windows 8 / Rstudio Version 1.1.442

here s the exact command line
SDC_LS_MAGG <- microaggregation(SDC_LS,variables = SDC_nV, method='mdav',measure='median', aggr=7);

Here s the full script

###---------------------------------INITIALIZE PARAMETERS
SDC_kV =  c("kV_1","kV_2","kV_3","kV_4"); SDC_kV = gsub(" ","", SDC_kV);
SDC_sV = NULL;	  	
SDC_nV =c("nV_1","nV_2");	SDC_nV = gsub(" ", "", SDC_nV);
SDC_gV = NULL;
SDC_stV = NULL;
SDC_pV = NULL;
SDC_wV = NULL;
SDC_eV = NULL;
###---------------------------------CREATE THE SDC OBJECT FROM A DATAFRAME
SDC <- createSdcObj(DF_SDC,keyVars=SDC_kV,numVars = SDC_nV,excludeVars =SDC_eV,sensibleVar = SDC_sV,ghostVars = SDC_gV ,strataVar = SDC_stV,pramVars =SDC_pV ,weightVar = SDC_wV);
###---------------------------------PRINT THE SDC OBJECT
SDC;
###---------------------------------LOCAL SUPPRESSION K=7 AND IMPORTANCE SET
SDC_importance=c(1,2,3,4)
SDC_LS <- localSuppression(SDC, k = 7,importance=SDC_importance);
###---------------------------------PRINT THE SDC_LS OBJECT
print(SDC_LS, "ls");
####---------------------------------MICROAGGREGATION AGG=7 MEASURE=MEDIAN METHOD=MDAV
SDC_LS_MAGG <- microaggregation(SDC_LS,variables = SDC_nV, method='mdav',measure='median', aggr=7);
####---------------------------------WRITE A CSV FILE - READABLE FOR TESTING PURPOSE
datafile_out = "SDC_LS_MAGG.csv"
path_datafile_out=paste(paste(getwd(),"SDC/microagg/work",sep='/'),datafile_out,sep='/')
writeSafeFile(obj=SDC_LS_MAGG, format="csv", randomizeRecords="no", sep="^", dec=".", col.names=TRUE, row.names=FALSE, quote = FALSE, fileOut=path_datafile_out);

here the description of the initial datafile
str(DF_SDC)
'data.frame':	330 obs. of  6 variables:
 $ kV_1: chr  "C" "C" "C" "C" ...
 $ kV_2: chr  "B" NA "F" NA ...
 $ kV_3: chr  "E" "D" "B" "D" ...
 $ kV_4: chr  "C" "H" "H" "G" ...
 $ nV_1: num  17 19 14 18 16 16 15 15 14 17 ...
 $ nV_2: num  0 34 0 33 0 35 0 0 39 0 ...

the input file (DF_SDC) is attached
[DF_SDC.zip](https://github.com/sdcTools/sdcMicro/files/2396269/DF_SDC.zip)
the output file (SDC_LS_MAGG) is attached
[SDC_LS_MAGG.zip](https://github.com/sdcTools/sdcMicro/files/2396275/SDC_LS_MAGG.zip)

**Comment by bernhard-da** [comment]
hi @superjeje  thx for reporting this. indeed, the measure-argument is ignored for `mdav` (as the underlying code does not support this feature) and `rmd`. I added a note to the documentation to make this clear.
