### ISSUE TITLE
GUI: sdcApp() can't open

### ISSUE THREAD

**Issue by janine112** [sdcTools/sdcMicro#268]
![default](https://user-images.githubusercontent.com/30063650/46842162-aba67400-cdfe-11e8-8832-3200d49902ef.PNG)

**Comment by bernhard-da** [comment]
hi @janine112. thx for reporting this. after issuing the command, your browser should open containing a tab with the sdcMicro graphical user-interface. if that is not happening, just open the url (`127.0.0.1:6491`) in your example with your favourite browser and it should work.
