### ISSUE TITLE
Bug due to update of haven package

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#273]
From version 2.0.0 of the haven package (release November 2018), labelled variables are imported as class "haven_labelled" instead of class "labelled". Variables of class "haven_labelled" aren'T converted to factor in sdcApp. Therefore, this class needs to be added. 

In order to accomodate for users of older and newer versions of the haven package, I suggest to keep both.

**Comment by bernhard-da** [comment]
@thijsbenschop pr merged, thx.
