### ISSUE TITLE
Publish sdcMicro on CRAN

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#274]
Hi,

since the last release of sdcMicro on May 16, 2018, there have been a couple of bug reports and fixes, especially related to the use of sdcApp. Currently, sdcApp doesn't work properly (if data with labels is loaded, they appear as haven_labelled, for example; the k-anonimity button is missing in certain cases). Therefore, I wanted to ask when the next release of sdcMicro is scheduled. It would be helpful if this could happen in the near future to ensure the proper functioning of sdcApp.

Thanks,

Thijs

**Comment by matthias-da** [comment]
Hi,

good idea.

We will work first to get rid of the errors, https://win-builder.r-project.org/dsZQ5wMe54s8/00check.log

They seem not to be critical, so I'm sure we can upload a version in beginning of next week.

Best,
Matthias

**Comment by thijsbenschop** [comment]
Great, thank you!

**Comment by thijsbenschop** [comment]
Hi,

is there any news on the release of sdcMicro on CRAN? As far as I can see the new version isn't available yet. Is it awaiting approval or are there any issues that need to be resolved? It would be great if the new version could become available soon, as people are using sdcApp and would benefit from updating sdcMicro.

**Comment by bernhard-da** [comment]
@thijsbenschop as we've said, an updated version will come soon. there is no need to bump this issue.

**Comment by thijsbenschop** [comment]
@bernhard-da, thank you, I just downloaded the source of version 5.4.0 from CRAN.
