### ISSUE TITLE
Unexpected SUDA attribute contribution

### ISSUE THREAD

**Issue by RaffaelBild** [sdcTools/sdcMicro#275]
Hello,

I noticed that the method `suda2()` computes unexpected attribute contributions in some cases. For example, when I execute the code

`require(sdcMicro)`
`a <- c(2, 1, 1)`
`b <- c(0, 3, 0)`
`c <- c(0, 6, 0)`
`data <- data.frame(a,b,c)`
`su <- suda2(data)`
`su`

with sdcMicro v5.3.0 and R v3.4.1, I obtain the following attribute contributions:

- - - - - - - - - - - 
  variable contribution
1        a         50.0
2        b         37.5
3        c         25.0
- - - - - - - - - - - 

However, when I inspect the example dataset

`a b c`
`2 0 0`
`1 3 6`
`1 0 0`

I find the following 1-MSUs, each of which contributes a SUDA score of 2 (letters denote the attributes and numbers the respective values):
`a2, b3, c6`
In addition, I find the following 2-MSUs, each of which contributes a SUDA score of 1:
`(a1; b0), (a1; c0)`
Based on these MSUs, I would expect the following attribute contributions:

 - - - - - - - - - - - 
  variable contribution
1        a         (2+1+1) / 8 * 100 = 50
2        b         (2+1) / 8 * 100 = 37.5
3        c         (2+1) / 8 * 100 = 37.5
- - - - - - - - - - - 

Is it possible that sdcMicro is not properly taking the MSU `(a1; c0)` into account when computing the variable contribution of attribute c?

**Comment by bernhard-da** [comment]
@RaffaelBild hi, thx for reporting this. we can reproduce and need to investigate further as to why this happens ....

**Comment by alexkowa** [comment]
Original IHSN C++ Code produces the same result.

**Comment by alexkowa** [comment]
The (Dis-)Suda Score was computed correctly, so this is unchanged. Only the attribution per variable was not correct and is now corrected.
