### ISSUE TITLE
Values of table/summary output wrong with missing values

### ISSUE THREAD

**Issue by matthias-da** [sdcTools/sdcMicro#283]
```{r}
library(simPop)
data(eusilc13puf)
require(sdcMicro)
obj$inputdata <- readMicrodata(path="eusilc13puf", type="rdf", convertCharToFac=FALSE, drop_all_missings=FALSE)
inputdataB <- inputdata

## Convert a string or factor variable to numeric
inputdata <- varToNumeric(obj=inputdata, var=c("age"))
## Set up sdcMicro object
sdcObj <- createSdcObj(dat=inputdata,
        keyVars=c("hsize","db040","rb090","pl031","pb220a"),
        numVars=c("age","pgrossIncome"),
        weightVar=c("weight"),
        hhId=NULL,
        strataVar=NULL,
        pramVars=NULL,
        excludeVars=NULL,
        seed=0,
        randomizeRecords=FALSE,
        alpha=c(0.5))

## Store name of uploaded file
opts <- get.sdcMicroObj(sdcObj, type="options")
opts$filename <- "eusilc13puf"
sdcObj <- set.sdcMicroObj(sdcObj, type="options", input=list(opts))
```

Here the table shown (in the sdcApp) shows frequencies of the smallest category of 0, but it should be a positive value. I think missing values are not accounted for in the right manner by calculating this table.

**Comment by matthias-da** [comment]
The results are not "wrong" but they should be changed. 
It happens of course when factors of size 0 are there like in

```{r}
table(eusilc13puf$pl031)
```

Thus the calculations are correct, but we should change the output internally.
To display "the smallest" category of size 0 does not make sense. Thus we need another check if factors are present including no observations. The smallest category should be the one with the smallest positive count.

**Comment by bernhard-da** [comment]
please check; we are now returning the smallest category > 0
