### ISSUE TITLE
Code from sdcApp not reproducible in sdcMicro

### ISSUE THREAD

**Issue by matthias-da** [sdcTools/sdcMicro#284]
For example after some clicks in sdcApp, we receive this code from the app:

```{r}
require(sdcMicro)
obj$inputdata <- readMicrodata(path="eusilc13puf", type="rdf", convertCharToFac=FALSE, drop_all_missings=FALSE)
inputdataB <- inputdata

## Convert a string or factor variable to numeric
inputdata <- varToNumeric(obj=inputdata, var=c("age"))
## Set up sdcMicro object
sdcObj <- createSdcObj(dat=inputdata,
        keyVars=c("hsize","db040","rb090","pl031","pb220a"),
        numVars=c("age","pgrossIncome"),
        weightVar=c("weight"),
        hhId=NULL,
        strataVar=NULL,
        pramVars=NULL,
        excludeVars=NULL,
        seed=0,
        randomizeRecords=FALSE,
        alpha=c(0.5))

## Store name of uploaded file
opts <- get.sdcMicroObj(sdcObj, type="options")
opts$filename <- "eusilc13puf"
sdcObj <- set.sdcMicroObj(sdcObj, type="options", input=list(opts))
```

We have to add manually

```{r}
library(simPop)
data(eusilc13puf)
```

New proposal:
The eusilc13puf data is only available after loading it to R before starting the sdcApp.
We need an import: import data from an installed R package. 

Nevertheless the line

```{r}
obj$inputdata <- readMicrodata(path="eusilc13puf", type="rdf", convertCharToFac=FALSE, drop_all_missings=FALSE)
```

will not work in sdcMicro (command line) because the object obj is only available after starting the sdcApp and selecting the data. Ideas to solve this?
Initially the gui was designed that one can learn Anonymization with the gui and then learn sdcMicro by copy and paste and editing the script (produced by the gui ) ready to work in the R console.

**Comment by GregorDeCillia** [comment]
If we find the time to do so, we could create the code via [shinymeta](https://github.com/rstudio/shinymeta) so issues with unrunnable code become less likely in the future. What do you think @bernhard-da ?

**Comment by bernhard-da** [comment]
@GregorDeCillia yes, if we find time this would be the best solution

@matthias-da for now, we already have `import from rdata`, so you can always save the input dataset beforehand. we could add a warning message to the script that in case you select a dataset from the workspace, it is expected that the file must be loaded also when an exported script from the app is sourced?

**Comment by matthias-da** [comment]
yeah, a warning would be fine and enough. 

The idea is to simple copy and paste the code produced by the app in the R console:
- if you didn't load the data, you get a proper error message in any case (data not found)
- if you loaded the data, everything should run.

This is not possible, when starting with 

```{r}
obj$inputdata <- readMicrodata(path=...
```

because the obj is not existing.

This could be avoided by adding a line

```{r}
obj <- NULL
```

but still then object inputdata is not found. In the previous case this would be

```{r}
inputdata <- eusilc13puf
```

Then everything would work with such a quick and dirty modification of the sdcApp's provided reproducibility code.

**Comment by bernhard-da** [comment]
fixed in https://github.com/sdcTools/sdcMicro/commit/498ade9c469095f32f93a75c76268ada7b1c40d7
