### ISSUE TITLE
object ‘knit_print.html’ is not exported by 'namespace:shiny'

### ISSUE THREAD

**Issue by TheRealSvc** [sdcTools/sdcMicro#287]
When installing from source on linux i got this error:

Error: object ‘knit_print.html’ is not exported by 'namespace:shiny'

With the last version (~1 month ago ) i had no probem. Since there was some cleanup with the imports, could it be something goes wrong ?

**Comment by matthias-da** [comment]
Have you tried it with sdcMicro version 5.4.1 (from GitHub).
The problem was with shiny, they changed some things in their package. 

A new version is already on the way to CRAN, and as mentioned above, the GitHub version should work.

**Comment by TheRealSvc** [comment]
Thanks ! Using the github version (like this: devtools::install_github("sdcTools/sdcMicro") ) worked.
