### ISSUE TITLE
k-anonymity summary fails to sink

### ISSUE THREAD

**Issue by kmsis2011** [sdcTools/sdcMicro#290]
Using sdcMicro. Ran a k-anonymity but  infos 2/3 -anonymity component of report fails to sink to a file. It is showing in red but throws no error or warning. 
![report_with_error](https://user-images.githubusercontent.com/1645467/73385937-084fcb80-429c-11ea-9640-687f1c42d6ab.png)

**Comment by kmsis2011** [comment]
Also using windows 10 for this. Error seems to have happened after upgrade to windows 10!?!

**Comment by bernhard-da** [comment]
hi @kmsis2011 

thx for reporting this. could you please provide a small, reproducable running example (using testdata from sdcMicro)?

**Comment by kmsis2011** [comment]
thx. See this 
[code_sdc_debugging.txt](https://github.com/sdcTools/sdcMicro/files/4130362/code_sdc_debugging.txt)
[sdc_debug_data.txt](https://github.com/sdcTools/sdcMicro/files/4130363/sdc_debug_data.txt)

data was in csv but it looks like this is not supported here for upload

**Comment by bernhard-da** [comment]
@kmsis2011 the issue is that `sink()` by default does not allow to redirect output generated using `message()` to a file. you can easily workaround this however, for example see [**here**](https://stackoverflow.com/questions/48173020/r-function-sink-isnt-redirecting-messages-or-warnings-to-a-file)

**Comment by kmsis2011** [comment]
Thanks. That works
