### ISSUE TITLE
report() function gives error when including sensibleVars in sdcObject

### ISSUE THREAD

**Issue by joppekb** [sdcTools/sdcMicro#291]
The report() functions gives the following error if I use it after including variables in sensibleVars.

Simple dataset used:

```r
library(sdcMicro)
df <- data.frame(ID = 1:10,
                 varSensitive = as.factor(rep(c("A", "B"), 5)),
                 varFactor = as.factor(rep(c("C", "D"), 5)))
sdc <- createSdcObj(dat = df, keyVars = "varFactor", sensibleVar = "varSensitive")
report(sdc)
#> Quitting from lines 55-69 (report-template.rmd) 
#> Error in paste(impVar$sensibleVar, collapse = "* | *") : 
#>   object 'impVar' not found 
```

I used SDCmicro Version 5.4.0. It gave me the same error when I used the Case study 1 and Case study 2 examples in the SDC practice guide.

If I did something wrong that caused this error I would love to know. 

Thank you!

**Comment by bernhard-da** [comment]
@joppekb thx for reporting, i have fixed the problem.
