### ISSUE TITLE
suda2 error on dataset with less than 3 categorical variables

### ISSUE THREAD

**Issue by undestu** [sdcTools/sdcMicro#292]
The R codes for the `suda2()` function suggest an intent to pad up dataframes such that they have at least 3 categorical variables for the SUDA assessment. However, this does not seem to be working as intended. Running any dataset with <3 categorical variables gives the following error:

```r
sdcMicro::suda2(mtcars[,1:2])
#> Error in addWarning(obj, warnMsg = warn_s, method = "suda2", variable = NA) : 
#>   object 'obj' not found
```

Glancing at the suda2 function R codes, the only reference to an object named "obj" occurs in an _if_ code block that is triggered when there are <3 categorical variables:

https://github.com/sdcTools/sdcMicro/blob/bc13d4ec7fa8de73a7ef76e809ddd1bb0da970ab/R/suda2.R#L159-L164

The object `obj` is not used in the function otherwise or returned. Can it be removed or corrected in future releases of sdcMico?

**Comment by GregorDeCillia** [comment]
Thanks for the error report. It seems like line 162 should read

```r
res <- addWarning(res, warnMsg = warn_s, method = "suda2", variable = NA) 
```

where `res` is the object that is eventually returned by `suda2()`. But since I am not familiar with the codebase of this package, I'll have to await feedback from @alexkowa or @bernhard-da

**Comment by GregorDeCillia** [comment]
I just found a similar line in

https://github.com/sdcTools/sdcMicro/blob/47f0436f680e090fb141d79c9fac134cd03fab0c/R/microaggregation.R#L234

where `obj` is not defined in the context of the corresponding function `microaggregationWORK()`. Those lines are not covered by the unit-tests: https://coveralls.io/builds/28514478/source?filename=R/microaggregation.R#L234
