### ISSUE TITLE
Error in createSdcObj and sdcApp if a data.table is used as input

### ISSUE THREAD

**Issue by alexkowa** [sdcTools/sdcMicro#293]
I just came across the problem that is not possible to start the process in the App with a preloaded data.table. The same is true and I guess this is the source of the error in general that it is not possible to create an SdcObj based on a data.table.
```
library(data.table)
library(sdcMicro
set.seed(1)
testdt <- data.table(a=sample(LETTERS,10),b=sample(LETTERS,10), id= 1:10)
so <- createSdcObj(testdt, keyVars=c("a","b"))
sdcApp()
```

**Comment by bernhard-da** [comment]
@alexkowa thx for reporting, will fix in a moment

**Comment by bernhard-da** [comment]
fixed in https://github.com/sdcTools/sdcMicro/commit/139f45d4f2f267e63f64c3b3487d62c4d3ce80d9
