### ISSUE TITLE
SUDA attribute level contributions when variable has NA as a level

### ISSUE THREAD

**Issue by undestu** [sdcTools/sdcMicro#296]
The suda2 function's output attribute_level_contribution does not seem to properly report a variable's attribute level risk when said variable has NA as a level. For eg:

```
df <- mtcars[, c("cyl", "am", "gear", "carb")]
df[1, "cyl"] <- NA
df_suda <- suda2(df, missing = NA)

df_suda$attribute_level_contributions
```

gives the result...

![Untitled](https://user-images.githubusercontent.com/19852691/82168903-745d4a80-98f2-11ea-9674-f88b0a25c827.png)

... where all the level risks for variable **cyl** are unexpectedly NA.

Can this be fixed in future updates to sdcMicro please?

**Comment by bernhard-da** [comment]
hi @undestu  thx for reporting. i pushed an update that should address the issue.
