### ISSUE TITLE
haven version 2.3.0 causes error on reading SPSS and STATA files in sdcApp

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#298]
The new haven release (2.3.0) adds the classes "vctrs_vctr" and "double" besides the class "haven_labelled" to factor variables. See example below (I can't add a STATA file for testing, but this happens to any STATA or SPSS file with labelled variables upon loading in R using read_sav or read_dta from the haven 2.3.0 package).

```
> class(test$gender)
[1] "haven_labelled" "vctrs_vctr"     "double"
```

The additional classes lead to a failure to detect the variables of class haven_labelled in line 458 of GUIfunctions.R. 

`#cl_lab <- which(sapply(res, class) %in% c("labelled", "haven_labelled"))`

Therefore, the variables of class haven_labelled are not converted to class factor, which in turn causes an error upon loading and processing the files in sdcApp.

![Screenshot 2020-06-15 at 12 07 49](https://user-images.githubusercontent.com/8253935/84645463-ea100280-af00-11ea-848e-42f76b501552.png)
![Screenshot 2020-06-15 at 12 07 13](https://user-images.githubusercontent.com/8253935/84645471-ebd9c600-af00-11ea-9ba2-dfe16d889500.png)

A solution is to ignore other classes of a variable besides the first class, e.g., by using

```  
cl_lab <- which(sapply(test, function(var){class(var)[1]}) %in% c("labelled", "haven_labelled"))
```

Then variables of class haven_labelled will be properly detected and converted to class factor.

**Comment by thijsbenschop** [comment]
See pull request #299

**Comment by bernhard-da** [comment]
@thijsbenschop thx for reporting, fixed.
