### ISSUE TITLE
Difference between pram and pram_strata?!

### ISSUE THREAD

**Issue by alexkowa** [sdcTools/sdcMicro#30]
ohne das jetzt ueberpruefen zu koennen - ich glaube der print output unterscheidet sich bei den beiden Funktionen, wobei pram() detailiertere Info gibt, zumindest falls nur eine Variable gepramt wird.

**Comment by bernhard-da** [comment]
should be closed

pram_strata and pram() were merged, additional print-output from pram() not really useful (only function parameters pd|alpha).

commits for sdcMicroGUI follow tomorrow...
