### ISSUE TITLE
ldiversity question

### ISSUE THREAD

**Issue by leebrian** [sdcTools/sdcMicro#300]
Hello, great package, thank you so much for making it.

I'm a little confused about how the `ldiversity` function works. I have a dataset with a sensitive factor with all NAs and the results of the ldiversity function show the risk as 1 for each record. I would expect that missing values do not count against ldiversity counts.

This code produces ldiversity of 2 for the two sensitive_vars with NA for the "Bar" quasi identifier, as expected.
```R
sample.data <- data.frame(
  quasi_identifier = c("Foo","Foo","Foo","Bar","Bar"),
  sensitive_var = c(1,1,1,NA,NA)
)
print(sample.data)
sdcObj <- createSdcObj(dat=sample.data,
                       keyVars=c("quasi_identifier"),
                       numVars=NULL,
                       weightVar=NULL,
                       hhId=NULL,
                       strataVar=NULL,
                       pramVars=NULL,
                       excludeVars=NULL,
                       seed=0,
                       randomizeRecords=FALSE,
                       alpha=c(0))
sdcObj
sdcObj <- ldiversity(obj=sdcObj, ldiv_index=c("sensitive_var"), l_recurs_c=2)
sdcObj@risk$ldiversity[,'sensitive_var_Distinct_Ldiversity']
> sdcObj@risk$ldiversity[,'sensitive_var_Distinct_Ldiversity']
[1] 1 1 1 2 2
```

But when I update the code above to use a dataset of 1.6M records with 5 quasi identifiers, there are many records that are part of a cell with only NA for the sensitive variable. For example, one cell of 10 records sharing the same quasi identifiers and NA for my sensitive variable, but the ldiversity results as 1 for each record. The `sdcObj@risk$individual[,2]` returns as 10 for each record.

Is there a way to include NA values as distinct for purposes of ldiversity?

**Comment by bernhard-da** [comment]
@leebrian sorry for the late reply; do you have a reproducable example given your "large" dataset? any chance that the key of the cell you were looking at had a `NA` as value in one of the quasi-identifiers? if so, it might have something to do with your choice of `alpha` in `createSdcObj()` as this parameter defines how key containing `NAs` are counted. you could check by setting `alpha = 1` (the default) and see, if the ldiv results change.

**Comment by leebrian** [comment]
Thanks for the response. I couldn't provide a good example earlier, but the dataset is now [public](https://data.cdc.gov/Case-Surveillance/COVID-19-Case-Surveillance-Public-Use-Data/vbim-akqf) so I'll try to recreate my example and post you something reproducible.
