### ISSUE TITLE
Error in : In sliderInput(): `min`, `max`, and `value` cannot be NULL, NA, or empty.

### ISSUE THREAD

**Issue by RonnOtt** [sdcTools/sdcMicro#312]
Hi,

thank you very much for this super GUI. I have only unfortunately a problem. When I start the sdcApp(), I can read in the test data and also edit it. But when confirming the button "Setup SDC Problem" the GUI crashes and R shows the following error:
Error in : In sliderInput(): `min`, `max`, and `value` cannot be NULL, NA, or empty.
R version : 4.0.5. and I reloaded sdcMicro over here: devtools::install_github("sdcTools/sdcMicro"). Operating system Mac and Windows. On older version it runs for me. A friend wanted to test it now with him the same error under R 3.6.1.
Thanks for the help.

Ronny

**Comment by bernhard-da** [comment]
hi @RonnOtt; thx for reporting this. I was able to reproduce and fix in 5a32b81. could you confirm that this indeed fixes the problem? thx.

**Comment by RonnOtt** [comment]
Hi, perfect . Problem solved. Thanks for the quick help. Everything works perfectly. thank you

**Comment by bernhard-da** [comment]
@RonnOtt thx for confirming that now everything works.
