### ISSUE TITLE
sdcApp doesn't work after upgrading to shiny 1.7.0 from 1.5.0

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#316]
Hi,

after upgrading to shiny version 1.7.0., the sdcApp shiny GUI no longer works. The following warning appears in the console:

![image](https://user-images.githubusercontent.com/8253935/150332118-6546a985-f9c9-4b15-bb4d-3f0c23c1f703.png)

The app launches, but after cselecting a dataset to work with (e.g., testdata), and selecting some key variables, the app freezes and the following error appears in the console:

![image](https://user-images.githubusercontent.com/8253935/150332287-f69db43b-742d-43f4-9271-b76398a44201.png)

It shows as a warning, but the app is no longer responsive. 

The issue is also described here: https://gitmetadata.com/repo/rstudio/bslib/issues/373

Downgrading to shiny 1.5.0. solves the issue (not to 1.6.0. though, then the issue persists).

**Comment by bernhard-da** [comment]
@thijsbenschop  i fixed the warning but could not reproduce the error with shiny 1.7.1; can you test again please?

**Comment by thijsbenschop** [comment]
@bernhard-da thanks for the quick fix, the warning has disappeared and the issue as described is also solved.
