### ISSUE TITLE
New guidelines vignette?

### ISSUE THREAD

**Issue by coatless** [sdcTools/sdcMicro#325]
From the 5.7.2 release, the [NEWS](https://github.com/sdcTools/sdcMicro/blob/cd9768363da5ef5289ef234f31f547a448cec141/NEWS#L2) entry indicates the `sdc_guidelines.pdf` vignette has been removed. 

Are there any plans to incorporate a new guidelines document?

**Comment by matthias-da** [comment]
There are plans but not on the short list. Currently we are too busy to write a new document, and the old one is quite outdated.

**Comment by bernhard-da** [comment]
there is also a document available at https://sdcpractice.readthedocs.io that is quite up-to-date (but not maintained/written by us).
