### ISSUE TITLE
sdcMicro package no longer available on CRAN

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#328]
Hi,

I noticed that the sdcMicro package was recently removed from CRAN? See https://cran.r-project.org/web/packages/sdcMicro/index.html

I wanted to ask whether this was intentional or an automatic process by CRAN. We rely on installing the package from CRAN and wanted to ask if it could remain available on CRAN.

Thanks,

Thijs Benschop

**Comment by bernhard-da** [comment]
@thijsbenschop  we are aware of this and the package will be on cran again soon.

**Comment by thijsbenschop** [comment]
@bernhard-da , great - thanks!
