### ISSUE TITLE
Package ‘sdcMicro’ was removed from the CRAN repository.

### ISSUE THREAD

**Issue by ArtificialTruth** [sdcTools/sdcMicro#329]
See more info on:
https://cran.r-project.org/web/packages/sdcMicro/index.html

**Comment by bernhard-da** [comment]
hi @ArtificialTruth  we know (https://github.com/sdcTools/sdcMicro/issues/328) and are currently working that `sdcMicro` is soon available on CRAN again.

**Comment by ArtificialTruth** [comment]
Ah sorry I only checked opened issues. Thanks so much!

**Comment by bernhard-da** [comment]
`sdcMicro` is finally back on CRAN; thx @matthias-da

**Comment by ArtificialTruth** [comment]
Since I had major dependency issues installing this package, I made a [docker image](https://github.com/ArtificialTruth/rserver_and_sdcmicro) to quickly install everything needed for this package. It's based on [rocker/rstudio](https://rocker-project.org/images/versioned/rstudio.html).
Perhaps you find it useful.

**Comment by bernhard-da** [comment]
hi @ArtificialTruth this might indeed be useful for some users; but would you mind describing the dependency issues you encountered?

**Comment by ArtificialTruth** [comment]
Several dependencies down the dependency tree required apt installs such as cargo for rust, gfortran and cmake, which was not installed on my Ubuntu system. See the full list here https://github.com/ArtificialTruth/rserver_and_sdcmicro/blob/main/Dockerfile#L12

**Comment by bernhard-da** [comment]
@ArtificialTruth ok i see; might indeed be helpful for somebody. i just tried it out for fun and the docker image works great!

**Comment by ArtificialTruth** [comment]
Glad to hear!
