### ISSUE TITLE
sdcMicro package no longer available on CRAN

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#341]
Hi,

I noticed that the sdcMicro package was recently removed from CRAN. See https://cran.r-project.org/web/packages/sdcMicro/index.html 

![image](https://github.com/sdcTools/sdcMicro/assets/8253935/61c434a5-68d0-48c1-8f5d-43112ee989aa)

I wanted to ask if you could give an estimate when the package will be again available on CRAN.

Thanks,

Thijs

**Comment by bernhard-da** [comment]
Hi, we are aware of the issue and @matthias-da is in the progress of getting sdcMicro back on CRAN. As they seem to change requirements all the time, it is difficult to give an estimate on when that will happen.
