### ISSUE TITLE
Problem downloading sdcMicro from CRAN

### ISSUE THREAD

**Issue by santiagopoy** [sdcTools/sdcMicro#345]
Dear all, I am not able to download sdcMicro from CRAN. 
"Package ‘sdcMicro’ was removed from the CRAN repository." (https://cran.r-project.org/web/packages/sdcMicro/index.html)

How do you suggest to install the package? I have RStudio version 4.3.2. Thanks!

**Comment by bernhard-da** [comment]
@santiagopoy thx for reporting. We are aware of the issue and working on it so that `sdcMicro` is soon again on CRAN. In the meantime you can install the lastest version from github directly using

```
devtools::install_github("sdcTools/sdcMicro")
```

**Comment by santiagopoy** [comment]
@bernhard-da thx! ```sdcMicro``` is now working!

**Comment by Bahamyirou** [comment]
Am not able to install sdcMicro from Cran neither. Is the issue fixed ? I have the most recent rstudio and the R-4.3.0 as well

**Comment by bernhard-da** [comment]
@Bahamyirou see my comment directly above yours.

**Comment by Bahamyirou** [comment]
@bernhard-da  the github installation did not work neither. Do we need a specific version of R ?

**Comment by bernhard-da** [comment]
@Bahamyirou what errors did you get when trying to install from github? Without any information it is impossible to help you.

**Comment by matthias-da** [comment]
No answers, closed.
