### ISSUE TITLE
GUI interface often freezes and does not refresh.

### ISSUE THREAD

**Issue by leodecarlo** [sdcTools/sdcMicro#348]
Hi,

Very often the GUI interface freezes and does not refresh.
The GUI still works but the specific page in use does not refresh anymore. For example, if I am in Anonymize,  the page will be off for ever.
Giving the http address in the console does not any  have effect, neither pasting the http address into the browser bar.

**Comment by bernhard-da** [comment]
@leodecarlo please provide a reproducable example (eg. using the export facility of the gui) so that I can have a look at this.

**Comment by leodecarlo** [comment]
@bernhard-da thanks for the reply. We were starting to use sdcMicro at Cineca as tool for data-anonymization in plaform for researcher and companies. In the last weeks I did not used since the project is in stand-by. But I have to start to train to coach other people. So I will remember to write here when happens.

**Comment by bernhard-da** [comment]
@leodecarlo ok, if you encounter specific issues with `sdcApp()`, please just re-open this issue. Thx.
