### ISSUE TITLE
what is individual risk measure rk?

### ISSUE THREAD

**Issue by leodecarlo** [sdcTools/sdcMicro#350]
Hi,

I am reading the page here https://sdcpractice.readthedocs.io/en/latest/measure_risk.html#categorical-key-variables-and-frequency-counts .

In table 1, what is and how it is computed rk 

> print(head(sdcInitial@origData))
  Residence Gender Educ Lstat Health Weights       risk fk  Fk
1         2      1    5     1      2     180 0.00542452  2 360
2         2      1    5     1      2     180 0.00542452  2 360
3         2      1    3     2      2     215 0.02509644  1 215
4         2      2    4     1      2      76 0.01256342  2 152
5         1      1    4     3      2     186 0.02824728  1 186
6         2      2    4     1      1      76 0.01256342  2 152
> 

I don't get it from the turorial. 

thanks
Leonardo

**Comment by thijsbenschop** [comment]
Hi @leodecarlo,

this repo is for the development of the R package sdcMicro. The guide you're referring to is on this repo: https://github.com/ihsn/SDCPractice/. If you find errors, please create an issue there. For clarifications on the content of the guide, please start a discussion there: https://github.com/ihsn/SDCPractice/discussions

**Comment by leodecarlo** [comment]
thanks

**Comment by matthias-da** [comment]
"I don't get it from the tutorial." 

You might consider to read 
https://link.springer.com/book/10.1007/978-3-319-50272-4

instead of a tutorial. The formula's behind are quite complicated (and in the book), but the result is in the first column.
You can also access it through:

```{r}
sdcInitial@risk$individual[,"risk"]
```

Best
Matthias

**Comment by leodecarlo** [comment]
Thanks,

I did not know this reference , I knew just the paper
https://www.jstatsoft.org/article/view/v067i04

I hope to find a way to get the book.

Leonardo
