### ISSUE TITLE
remove references to pram_strata in vignette/guidelines

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/sdcMicro#36]
since there is now no function pram_strata(), we have to options to deal with this situation in the docs.

1) remove all references to pram_strata() with correct code
2) add a wrapper function pram_strata() that just calls pram()

the same has to be done for references to the "old" pram function, since parameters have been changed.

thoughts?

**Comment by alexkowa** [comment]
set pram_strata (the wrapper) to deprecated
