### ISSUE TITLE
kein Update der Frequency Counts after globalRecode

### ISSUE THREAD

**Issue by matthias-da** [sdcTools/sdcMicro#39]
require(sdcMicro); data(testdata)
sdc <- createSdcObj(testdata, 
        keyVars=c('urbrur','water','sex','age'), 
        numVars=c('expend','income','savings'), 
        w='sampling_weight', hhId='ori_hid')
length(table(sdc@manipKeyVars[,"age"])) #OK
p1 <- print(sdc)
sdc <- globalRecode(sdc, column="age",
        breaks=c(1,9,19,29,39,49,59,69,100), labels=1:8)
length(table(sdc@manipKeyVars[,"age"])) #OK
p2 <- print(sdc)

identical(p1,p2)

**Comment by matthias-da** [comment]
obj <- calcRisks(obj) 
in setMethod in globalRecode hinzugefuegt. --> package now newly checked. Why it had worked with sdcMicroGUI?

**Comment by matthias-da** [comment]
obj <- calcRisks(obj)
had no effect. Don't know why...Alex?

**Comment by bernhard-da** [comment]
i think it should be 

obj <- measure_risk(obj) 

instead of calcRisks()

**Comment by alexkowa** [comment]
Probably it is triggered in the GUI separately. =>check if it runs twice now
Am 28.11.2013 14:35 schrieb "Matthias Templ" notifications@github.com:

**Comment by bernhard-da** [comment]
furthermore, p1 and p2 are always equal since the print function only returns NULL :)

**Comment by matthias-da** [comment]
OK ;) 

But if measure_risk() is the solution, localSuppression, localSupp2 and LocalRegProg still have calcRisks()  and there it work perfectly. I think we should be consistent and always use calcRisks().

**Comment by bernhard-da** [comment]
right :)

just tried with calcRisks() again and now it seems to be working. have you checked only the result of identical() or also the print output? if the former, you can revert my commit...

**Comment by matthias-da** [comment]
revert: the former.
