### ISSUE TITLE
Error message for sdcMicroGUI when using RStudio

### ISSUE THREAD

**Issue by statzhero** [sdcTools/sdcMicro#44]
I just installed XQuartz and GTK+ on OS X 10.9.1 but get the following error message:
( I restarted R of course.)

The GTK+ installation screen keeps prompting.

```
If the package still does not load, please ensure that GTK+ is installed and that it is on your PATH environment variable
IN ANY CASE, RESTART R BEFORE TRYING TO LOAD THE PACKAGE AGAIN
Loading required package: gWidgets
Error : .onAttach failed in attachNamespace() for 'gWidgetsRGtk2', details:
  call: .Call(name, ..., PACKAGE = PACKAGE)
  error: "S_gtk_icon_factory_new" not available for .Call() for package "RGtk2"
In addition: Warning message:
Failed to load RGtk2 dynamic library, attempting to install it. 
Error: package ‘gWidgetsRGtk2’ could not be loaded
```

**Comment by bernhard-da** [comment]
hi. i thing the error message is pretty clear and has nothing to do with sdcMicro(GUI) but with gWidgetsRGtk2. Perhaps you should file a bug-report for this package.

**Comment by statzhero** [comment]
OK, and the GUI relies on it?

**Comment by bernhard-da** [comment]
yes. sdcMicroGUI uses gWidgetsRGtk2 to draw the interface.

**Comment by statzhero** [comment]
@bernhard-da is it possible that gWidgetsRGtk2 only runs on Windows? Doubt it and sorry I have never seen this package. 

I sent Michael Lawrence a message.

**Comment by bernhard-da** [comment]
@statshero no it should work, just google for instructions. i just found this one (https://www.stat.auckland.ac.nz/~kimihia/rgtk2) which is slightly outdated but generally it should work. but i don't have a mac to test it.

**Comment by statzhero** [comment]
thanks, also getting a mail delivery status for lawremi at lastate.edu, so no report after all.

**Comment by statzhero** [comment]
Nice, it worked now. I think the gWidgetsRGtk2 installed the wrong version of GTK+.

**Comment by bernhard-da** [comment]
very good. then i can close this!
