### ISSUE TITLE
Problem when loading script

### ISSUE THREAD

**Issue by dezopp** [sdcTools/sdcMicro#48]
I have installed all required packages for sdcMicroGUI and it seems that it works OK but when i try to select variables to be categorical, numerical, weight etc and when i click OK windows appear and it shows script running but it never finishes. and in the R console appears
Error in measure_riskWORK(manipData, keyVars, w = w, hid = hhId, ...) : 
  Please define valid key variables
What is the problem?
Thanks

**Comment by bernhard-da** [comment]
hi dezopp. first off, thanks for reporting this issue.

to solve your problem we probably need a few more things. 
1) which version of the packages are you running?

``` r
packageVersion("sdcMicro")
packageVersion("sdcMicroGUI")
```

2) can you give us a reproducible example (which data did you load, which variables did you choose as (categorical/numerical) key variables, weight variable,...? 

3) out of the blue I would guess that you did not specify any categorical key variables (which are used to calculate risks). Can you verify that?

**Comment by dezopp** [comment]
1) sdcMicroGUI 1.1.1
2) i used testdata that is available with the package
-categorical key variables: sex
-numerical key variables: income
-weight:samplin_weight

Thanks

**Comment by dezopp** [comment]
sdcMicro 4.3

**Comment by bernhard-da** [comment]
should now be fixed. it would be nice if you could test it out by installing the current github version of sdcMicro and test, if you problem has really been fixed so that we can close this issue and upload a new version to cran.

``` r
require(devtools)
install_github("sdcMicro", "alexkowa")
```

**Comment by dezopp** [comment]
i test it with the same dataset "testdata" and i found a problem when i select a weight variable , then the script is not running, i tried also with another dataset and i have the same problem.
The second problem is that if a have just selected a numerical key variables (without categorical key variables) the script is not working, and if i select at least one categorical together with the numerical than it works.

**Comment by bernhard-da** [comment]
hi. thx for reporting back. i just pushed a fix to sdcMicroGUI which makes sure, that at least one categorical key variable is selected.

**Comment by dezopp** [comment]
what about the problem with weight?

**Comment by bernhard-da** [comment]
hi. what is exactly the problem with the weights? if you just choose a weight variable, it will not work but you will get an popup saying you should specify at least one categorical key variable. if you do so, it does work (i just tested this with testdata).

could you paste the script (script -> export) so that we can reproduce the problem? thx

**Comment by dezopp** [comment]
I can't send you the scipt here becouse it support just png, gif or jpg but this is the codes:
set.seed( 942107 )
activedataset <- testdata
sdcObject <- createSdcObj(activedataset,keyVars=c('urbrur'),numVars=c('income'),weightVar=c('sampling_weight'))

And in the R Console i get this:
Error in setkeyv(dat, keyVars) : 
  some columns are not in the data.table: urbrur

**Comment by bernhard-da** [comment]
thx, i just tried it and the problem is the error i fixed yesterday. so with the current git-version everything is ok. have you installed the latest git-version of sdcMicro and sdcMicroGUI?

``` r
install_github("sdcMicro", "alexkowa")
```

**Comment by dezopp** [comment]
first i run: 

require(devtools)

and i get this in the R Console:
Loading required package: devtools
Attaching package: ‘devtools’
The following objects are masked from ‘package:utils’:
    ?, help
The following object is masked from ‘package:base’:
    system.file

Next i run:

install_github("sdcMicro", "alexkowa")

and i cet this in R Console:

Installing github repo sdcMicro/master from alexkowa
Downloading master.zip from https://github.com/alexkowa/sdcMicro/archive/master.zip
Error in function (type, msg, asError = TRUE)  : couldn't connect to host

next i download from the https://github.com/alexkowa/sdcMicro/archive/master.zip manually and instal manually but when i install manually i don't get any information in the R Console except:

utils:::menuInstallLocal()

so i don't now if i install the new version.

**Comment by bernhard-da** [comment]
are you behind a proxy? -> if so, the following might help

``` r
install.packages("httr")
library(devtools)
library(httr)
set_config(use_prox(url="http://your.proxy",port=1234,username="xxx",password="yyy")) 
install_github("sdcMicro", "alexkowa)
install_github("sdcMicroGUI", "alexkowa)
```

where you have to substitute url, port and optionally username and password for your values.

**Comment by dezopp** [comment]
i have the package httr  , but I'm not very familiar with this url and port, little help how to find then and a short example of set_config(...)

Thanks

**Comment by bernhard-da** [comment]
it is a bit difficult to help you from here. but it definately has to do something with your connection, but the issue you have reported is fixed. 

if you are not able to install from github you have to wait until we send a new version to cran (which will be soon i suppose).

**Comment by dezopp** [comment]
Thanks,
I will wait for the new version .

On Wed, Apr 9, 2014 at 3:10 PM, bernhard-da notifications@github.comwrote:

> it is a bit difficult to help you from here. but it definately has to do
> something with your connection, but the issue you have reported is fixed.
> 
> if you are not able to install from github you have to wait until we send
> a new version to cran (which will be soon i suppose).
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/alexkowa/sdcMicro/issues/48#issuecomment-39961441
> .

## 

Dejan Peeski
e-mail: dejan.peeski@stat.gov.mk
           dejanpeeski@gmail.com
           dejanpeeski@hotmail.com
tel. mob : 078 225 627
      work :02 3295 825
      home:048 414 699
