### ISSUE TITLE
mdav

### ISSUE THREAD

**Issue by matthias-da** [sdcTools/sdcMicro#51]
Based on Joerg Drechslers e-mail to us, reporting a problem with mdav. 

microaggregation gives wrong results for method mdav (old slow version and IHSN version) for the following toy data:

``` r
library(sdcMicro)
toyData <- data.frame(x=c(2,3,3,20,21), y=c(1,2,2,19,20))
toyData
   x  y
1  2  1
2  3  2
3  3  2
4 20 19
5 21 20
```

The result should be:

``` r
1  2.666667  1.666667
2  2.666667  1.666667
3  2.666667  1.666667
4  20.500000 19.500000
5  20.500000 19.500000
```

However, the outcome is:

``` r
m3 <- microaggregation(toyData, method="mdav", aggr=2)
m3$mx ## wrong!
m3$mx
     x    y
1  2.5  1.5
2  3.0  2.0
3  2.5  1.5
4 20.5 19.5
5 20.5 19.5
```

wrong. 

By the way, the old version gives the correct values but the ordering of observations is not correct:

``` r
m3 <- microaggregation(toyData, method="mdavold", aggr=2)
m3$mx ## wrong!
m3$mx
        [,1]      [,2]
3   2.666667  1.666667
4  20.500000 19.500000
5  20.500000 19.500000
31  2.666667  1.666667
41  2.666667  1.666667
```

**Comment by alexkowa** [comment]
Maybe the algorithm works to use only k observations and the observation x=3,y=2 in mx is the result of averaging over observation 2 and 3 in the data set?

**Comment by matthias-da** [comment]
good point but it does not hold:

``` r
library(sdcMicro)
toyData <- data.frame(x=c(2,3,3.1,20,21), y=c(1,2,2.1,19,20))
toyData
m3 <- microaggregation(toyData, method="mdav", aggr=2)
m3$mx 
m3$mx
     x    y
1  2.5  1.5
2  2.5  1.5
3  3.1  2.1
4 20.5 19.5
5 20.5 19.5

```

**Comment by alexkowa** [comment]
This seems to be a bug, when u have exactly some odd numbers as number of rows, strange
for(n in 4:100){
  toyData <- data.frame(x=round(10_rnorm(n),2), y=round(10_rnorm(n),2))
  m3 <- microaggregation(toyData, method="mdav", aggr=2)
  ident <- round(m3$mx,2)==toyData
  ident <- ident[,1]&ident[,2]
  if(any(ident)){
    print(summary(ident))
    cat(n,"Unique Obs like in orig data \n")
  }
}

toyData <- data.frame(x=round(10_rnorm(5),2), y=round(10_rnorm(5),2))
toyData
m3 <- microaggregation(toyData, method="mdav", aggr=2)
m3$mx
any(round(m3$mx,2)==toyData)

toyData <- data.frame(x=round(10_rnorm(7),2), y=round(10_rnorm(7),2))
toyData
m3 <- microaggregation(toyData, method="mdav", aggr=2)
m3$mx
any(round(m3$mx,2)==toyData)
