### ISSUE TITLE
modRisk

### ISSUE THREAD

**Issue by matthias-da** [sdcTools/sdcMicro#54]
Function for modRisk (instead of LLmodGlobalRisk) uploaded.

Two issues:
- still an error with testdata2
- replace LLmodGlobalRisk with modRisk, also for sdcMicro objects.

**Comment by matthias-da** [comment]
Beispiel fuer help file (not included yet)

libraray(laeken)
data(eusilc)
keyVars <- c("db040", "hsize", "rb090", "age", "pb220a", "pl030")
form <- as.formula(paste(" ~ ", "db040 + hsize + rb090 + 
             age + pb220a + age:rb090 + age:hsize + 
             hsize:rb090")) 
standardLLM <- as.formula(paste(c("fk", 
                      as.character(f)), 
                      collapse = ""))
standardLLM
pseLLM <- as.formula(paste(c("Nk", 
                      as.character(f)), 
                      collapse = ""))
pseLLM
weightedLLM <- as.formula(paste(c("fk", 
                    as.character(as.formula(
                      paste(c(f,"Fk"),
                            collapse="+")))), 
                            collapse = ""))
weightedLLM
(modRisk(eusilc, method = "standard", weights = eusilc$rb050, 
         formulaM = form, keyVars, bound = 5)) 
(modRisk(eusilc, method = "CE", weights =  eusilc$rb050, 
         formulaM = form, keyVars, bound = 5)) 
(modRisk(eusilc, method = "PML", weights = eusilc$rb050, 
         formulaM = form, keyVars, bound = 5)) 
(modRisk(eusilc, method = "weightedLLM", weights = eusilc$rb050, 
         formulaM = form, keyVars, bound = 5))

**Comment by matthias-da** [comment]
``` r
libraray(laeken)
data(eusilc)
keyVars <- c("db040", "hsize", "rb090", "age", "pb220a", "pl030")
form <- as.formula(paste(" ~ ", "db040 + hsize + rb090 + 
             age + pb220a + age:rb090 + age:hsize + 
             hsize:rb090")) 
standardLLM <- as.formula(paste(c("fk", 
                      as.character(f)), 
                      collapse = ""))
standardLLM
pseLLM <- as.formula(paste(c("Nk", 
                      as.character(f)), 
                      collapse = ""))
pseLLM
weightedLLM <- as.formula(paste(c("fk", 
                    as.character(as.formula(
                      paste(c(f,"Fk"),
                            collapse="+")))), 
                            collapse = ""))
weightedLLM
(modRisk(eusilc, method = "standard", weights = eusilc$rb050, 
         formulaM = form, keyVars, bound = 5)) 
(modRisk(eusilc, method = "CE", weights =  eusilc$rb050, 
         formulaM = form, keyVars, bound = 5)) 
(modRisk(eusilc, method = "PML", weights = eusilc$rb050, 
         formulaM = form, keyVars, bound = 5)) 
(modRisk(eusilc, method = "weightedLLM", weights = eusilc$rb050, 
         formulaM = form, keyVars, bound = 5)) 
```

**Comment by bernhard-da** [comment]
@matthias-da where is the code for `modRisk()`?

**Comment by bernhard-da** [comment]
in https://github.com/bernhard-da/sdcMicro/blob/master/R/modRisk.R there is an updated version, also for sdcMicroObj. 
- \+ generalization (does not depend on keyVars, but on the vars that are specified in the model)
- \+ new print-method
- \+ updated examples

if this is ok, we could deprecate `LLmodGlobalRisk`

**Comment by matthias-da** [comment]
+1 (depricate LLmodRiskGlobal)

**Comment by matthias-da** [comment]
Bernhard, this means that we can close the issue. Right?

**Comment by bernhard-da** [comment]
@matthias-da my changes from 2015 somehow were not merged; please have a look at pr https://github.com/sdcTools/sdcMicro/pull/304 

after this is merged we can close this.

**Comment by matthias-da** [comment]
merged and closed.
