### ISSUE TITLE
OK and Cancel button ordering

### ISSUE THREAD

**Issue by alexkowa** [sdcTools/sdcMicro#6]
OK and cancel in the same order. in some windows Cancel is left to OK, in
some it is right to OK. -- Suchen, wo!?!?

**Comment by alexkowa** [comment]
I searched through all the windows, but did not find anything...?!

**Comment by bernhard-da** [comment]
zb global recoding window: OK | Hilfe anstelle von Hilfe | OK

**Comment by alexkowa** [comment]
Die Reihenfolge sollte eigentlich immer OK | Cancel | Help sein, in dem Beispiel gibt es halt kein Cancel...?!

**Comment by bernhard-da** [comment]
ok, intuitiv waer fuer mich der ok-button immer ganz recht. aber das denk
ich, ist kosmetik^2 und daher egal.
