### ISSUE TITLE
Option "bottom" in topBotCoding recodes as "top"

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#61]
The function topBotCoding doesn't react to "bottom" in the argument kind and topcodes. See example below.

> a <- topBotCoding(c(1,2,3,4,5,6,7,8,9,10), value = 7, replacement = 99, kind="top")
> a
>  [1]  1  2  3  4  5  6  7 99 99 99
> b <- topBotCoding(c(1,2,3,4,5,6,7,8,9,10), value = 3, replacement = 99, kind="bottom")
> b
>  [1]  1  2  3 99 99 99 99 99 99 99

**Comment by bernhard-da** [comment]
hi @thijsbenschop 

thx for bringing up this issue which is now fixed. please install the package directly from github (using devtools) until an updated version is available from cran! thx.

**Comment by thijsbenschop** [comment]
Thank you for the quick fix!
