### ISSUE TITLE
Use of sensibleVar argument in createSdcObj

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#63]
There is a possibility to specify sensitive variables for the computation of l-diversity in the function createSdcObj. Could you please advice how l-diversity is computed based on the variable(s) in that slot. Should it be computed automatically? I only get the result, when I specify the sensitive variables again in the ldiv_index argument in the ldiversity function. 

Thanks,

Thijs

I attach an example:

```
library(sdcMicro)
# Set up dataset
data4 <- as.data.frame(cbind(
  as.factor(c('Urban', 'Urban', 'Urban', 'Urban', 'Rural', 'Urban', 'Urban', 'Urban', 'Urban', 'Urban')),
  as.factor(c('Female', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Female')),
  as.factor(c('Sec in', 'Sec in', 'Prim in', 'Sec com', 'Sec com', 'Sec com', 'Prim com', 'Post-sec', 'Sec in', 'Sec in')),
  as.factor(c('Emp', 'Emp', 'Non-LF', 'Emp', 'Unemp', 'Emp', 'Non-LF', 'Unemp', 'Non-LF','Non-LF')),
  as.factor(c('yes', 'yes', 'yes', 'yes','yes', 'no', 'no', 'yes', 'no', 'yes')),
  c(180, 180, 215, 76, 186, 76, 180, 215, 186, 76)))

names(data4) <- c('Residence', 'Gender', 'Educ', 'Lstat', 'Health', 'Weights')
sdc4 <- createSdcObj(dat = data4, 
  keyVars = c('Residence', 'Gender', 'Educ', 'Lstat'), 
  weightVar = 'Weights')

#### l-diveristy #####
sdc4 <- ldiversity(obj = sdc4, ldiv_index = c("Health"), l_recurs_c=2, missing = NA)
sdc4@risk$ldiversity
--------------------------
L-Diversity Measures 
--------------------------
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    1.0     1.0     1.0     1.4     2.0     2.0 

### l-diversity with sensibleVar argument ####
sdc5 <- createSdcObj(dat = data4, keyVars = c('Residence', 'Gender', 'Educ', 'Lstat'), weightVar = 'Weights', sensibleVar="Health")
sdc5 <- ldiversity(sdc5)
Error in ldiversityWORK(data = o, keyVars = kV, l_recurs_c = l_recurs_c,  : 
  argument "ldiv_index" is missing, with no default
sdc5 <- ldiversity(sdc5, ldiv_index = c("Health"))
sdc5@risk$ldiversity
--------------------------
L-Diversity Measures 
--------------------------
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    1.0     1.0     1.0     1.4     2.0     2.0 
```

**Comment by bernhard-da** [comment]
Hi, I just commited a possible fix to this issue.

If you specify directly a variable it will be used. If not, the variable in slot _sensibleVar_ of the sdcMicroObj-object will be used as sensitive variable.

Please install the latest version from github and report back, if this indeed fixes your issue so that we can close this bugreport.

**Comment by thijsbenschop** [comment]
Hi, thanks, with version v4.6.7. I get the same problem. ldiversity requires the ldiv_index argument. Also, the ldiversity measure is not automatically computed.

> rm(list=ls())
> 
> # Set up dataset
> 
> data4 <- as.data.frame(cbind(
> -   as.factor(c('Urban', 'Urban', 'Urban', 'Urban', 'Rural', 'Urban', 'Urban', 'Urban', 'Urban', 'Urban')),
> -   as.factor(c('Female', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Female')),
> -   as.factor(c('Sec in', 'Sec in', 'Prim in', 'Sec com', 'Sec com', 'Sec com', 'Prim com', 'Post-sec', 'Sec in', 'Sec in')),
> -   as.factor(c('Emp', 'Emp', 'Non-LF', 'Emp', 'Unemp', 'Emp', 'Non-LF', 'Unemp', 'Non-LF','Non-LF')),
> -   as.factor(c('yes', 'yes', 'yes', 'yes','yes', 'no', 'no', 'yes', 'no', 'yes')),
> -   c(180, 180, 215, 76, 186, 76, 180, 215, 186, 76)))
> 
> names(data4) <- c('Residence', 'Gender', 'Educ', 'Lstat', 'Health', 'Weights')
> sdc4 <- createSdcObj(dat = data4, 
> -                      keyVars = c('Residence', 'Gender', 'Educ', 'Lstat'), 
> -                      weightVar = 'Weights')
>   sdc4 <- ldiversity(obj = sdc4, l_recurs_c=2, missing = NA)
>   Error in .local(obj, ldiv_index, l_recurs_c, missing, ...) : 
>   argument "ldiv_index" is missing, with no default
>   sdc4@risk$ldiversity
>   NULL

**Comment by thijsbenschop** [comment]
This is what I meant to send:

```
### l-diversity with sensibleVar argument ####
sdc5 <- createSdcObj(dat = data4, keyVars = c('Residence', 'Gender', 'Educ', 'Lstat'), weightVar = 'Weights', sensibleVar="Health")
sdc5@risk$ldiversity
NULL
sdc5 <- ldiversity(sdc5)
Error in .local(obj, ldiv_index, l_recurs_c, missing, ...) : 
  argument "ldiv_index" is missing, with no default
sdc5@risk$ldiversity
NULL
```

**Comment by bernhard-da** [comment]
Hi @thijsbenschop 

could you try again with the latest version i just sent to github and report back? Thx.

**Comment by thijsbenschop** [comment]
Thanks for fixing this. Now (v 4.6.8) ldiversity works without specifying the ldiv_vars, when specifying the sensibleVar argument in createSdcObj as my previous example code.

Thanks!
