### ISSUE TITLE
Missing values in rankSwap

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#66]
Hi,

when using rankSwap with missing values in the variable(s) to be swapped, NA is replaced by -999 (unless another value is specified in the argument missing). I assume that the reason is that the underlying R code cannot handle the NA values. I have two questions:
- would it be possible to include in the rankSwap function that those values are coded back after swapping (-999 -> NA)? This would be an enhancement for the user. Perhaps, the missing argument can be picked automatically in such a way that it is out of the value range(s) of the swapped variable(s)?
- does the value -999 influence the computed correlation structure? Or in other words, would the outcome change when specifying another replacement value?

Thanks

**Comment by bernhard-da** [comment]
Hi. Thanks for bringing this up.

I modified the method a bit so that you can now also set missing=NA if your missing-values are already coded as NA. This also returns NA-values back.

As shown in the example above, the choice of values for missing has no impact in the result.

``` r
# prepare testdata with missing values
data(testdata2)
testdata2$income[sample(1:nrow(testdata2), 20)] <- NA
testdata2$expend[sample(1:nrow(testdata2), 20)] <- NA
testdata2$savings[sample(1:nrow(testdata2), 20)] <- NA
not_na <- !is.na(testdata2[,vars])

seed <- 10
vars <- c("income","expend","savings")

data_swap0 <- rankSwap(testdata2,seed=seed,missing=NA,variables=vars)[,vars]
data_swap1 <- rankSwap(testdata2,seed=seed,missing=-999,variables=vars)[,vars]
data_swap2 <- rankSwap(testdata2,seed=seed,missing=-9999,variables=vars)[,vars]
data_swap3 <- rankSwap(testdata2,seed=seed,missing=-99999,variables=vars)[,vars]
data_swap4 <- rankSwap(testdata2,seed=seed,missing=-999999,variables=vars)[,vars]
data_swap5 <- rankSwap(testdata2,seed=seed,missing=5.2345,variables=vars)[,vars]

identical(data_swap0[not_na], data_swap1[not_na])
[1] TRUE
identical(data_swap0[not_na], data_swap2[not_na])
[1] TRUE
identical(data_swap0[not_na], data_swap3[not_na])
[1] TRUE
identical(data_swap0[not_na], data_swap4[not_na])
[1] TRUE
identical(data_swap0[not_na], data_swap5[not_na])
[1] TRUE
```

So we get identical results for all non-missing observations independent on the choice of parameter _missing_.  While in principle it would be no problem to omit the argument _missing_, we still leave it for compatibility reasons. 

Please check with sdcMicro 4.6.9 from github and report back so that we can close this issue.

**Comment by thijsbenschop** [comment]
Hi,

thanks for this fix. It works as expected and I think this is a real enhancement for the user of rankSwap. I still have a few questions/suggestions:
- will the default missing be -999? Most users have probably NA as missing value, so changing the default might be helpful.
- if the data contains NAs and missing = -999, those NAs are replaced by -999. Shouldn't in this case only those -999's be interpreted as missing (removed from the swapping procedure) and perhaps an error appear (NA in data)?

**Comment by bernhard-da** [comment]
hi. 

1) the default value has changed to NA.
2) this is not the case the procedure works. basically the only thing the _missing_ argument does is to specify a code for NA values in the swapped dataset. If one has a special categorie (missing) in the input data, it is the users task to recode them properly i guess.

**Comment by thijsbenschop** [comment]
Thanks for changing the default value. I see, so if -999 would be my missing value code, I  would have to recode this to NA before using rankSwap. Perhaps in the help file to rankSwap, this could be specified in a similar way as in the ldiversity help: missing - an (integer) value to be used as missing value in the C++ routine instead of NA

**Comment by bernhard-da** [comment]
Yes. You would have to recode them to NA beforehand.
I have updated the documentation and am now closing this issue.
