### ISSUE TITLE
report function after groupVars

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#69]
Hi,

I tried to use the report function (internal) after using the groupVars function. There appears to be a problem with different factor levels before and after using the groupVars function. The error is 

```
> report(sdc)
Error in Ops.factor(left, right) : level sets of factors are different
```

When I do the recoding manually, the factor levels stay the same and the report function works (no observations for the old factor levels).

Could you please have a look, whether it is possible to change the report function to allow for different sets of factor levels before and after recoding in categorical key variables?

Thanks!

I replicated the error with the example code in the help file to the report function:

```
data(testdata2)
# Factor variable relat
class(testdata2$relat)
testdata2$relat <- factor(testdata2$relat, c(1,2,3,4,5,6))
class(testdata2$relat)
levels(testdata2$relat)

# Regroup with groupVars()
sdc <- createSdcObj(testdata2,
                    keyVars=c('urbrur','roof','walls','water','electcon','relat','sex'),
                    numVars=c('expend','income','savings'), w='sampling_weight')
levels(sdc@manipKeyVars$relat)
sdc <- groupVars(sdc, "relat", c(3,4,5,6), c(3,3,3,3))
levels(sdc@manipKeyVars$relat)
report(sdc)

# Regroup manually
sdc <- createSdcObj(testdata2,
                    keyVars=c('urbrur','roof','walls','water','electcon','relat','sex'),
                    numVars=c('expend','income','savings'), w='sampling_weight')
levels(sdc@manipKeyVars$relat)
sdc@manipKeyVars[sdc@manipKeyVars$relat %in% c(3,4,5,6), "relat"] <- 3
levels(sdc@manipKeyVars$relat)
report(sdc)
```

**Comment by bernhard-da** [comment]
hi. thx for reporting should be fixed now.
