### ISSUE TITLE
suda2 output

### ISSUE THREAD

**Issue by matthias-da** [sdcTools/sdcMicro#71]
from: chan_wen_chang@singstat.gov.sg

My department is exploring the use of SUDA2 in sdcMicro. We are amazed at how fast it is compared to Dr Mark Elliot’s SUDA program.

However, Dr Elliot’s SUDA program provides some interesting statistics. We are wondering if your team can consider including them into the SUDA2 function.

The statistics that we are interested:

1) Attribute contribution – This shows how much of the total risk is contributed by each attribute.
Example:
col#1 att 'RELT_TO_HD'                 percentage contribution               19.1964
col#2 att 'MIE_EXC_NAV_IND'   percentage contribution               1.7857
col#3 att 'AGE'                                   percentage contribution               86.3839
col#4 att 'SEX'                                    percentage contribution               1.5625
col#5 att 'MARITAL_ST'                  percentage contribution               10.2679

2) Attribute level contribution - This shows which attribute level is risky.
Example:
col#3 att 'AGE'=20            percentage contribution               0.4464
col#3 att 'AGE'=21            percentage contribution               1.1161
col#3 att 'AGE'=22            percentage contribution               0.8929
col#3 att 'AGE'=23            percentage contribution               2.2321
col#3 att 'AGE'=24            percentage contribution               0.8929
col#3 att 'AGE'=25            percentage contribution               1.5625

3) Number of MSU size k – This shows the number of MSU size k in the file.
Example:
3              Minimal Sample Uniques size 1
415         Minimal Sample Uniques size 2

We find that these statistics are useful in our SDC work. We would appreciate if you can advise on how to obtain these statistics from the SUDA2 outputs, or include them in the next version of sdcMicro.

**Comment by bernhard-da** [comment]
in acd66392b587a5e266d43fff66bd46e44645f4a9 i extended the suda2-class definition by including two additional data.frames. the data.frame (`attribute_contributions`) contains the contributing risks for each variable (solving 1) while `attribute_level_contributions` contains the for each level of the variables the contributing risk (solving 2).

extracting the information required in 3) will need more work.
