### ISSUE TITLE
suda(2) treatment of missing and overview

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#74]
In the dis-suda summary, the records that aren't sample uniques nor special uniques (score 0) are reported as having a score larger than zero. These records should either not appear in the table or have their own category (=0 / not sample unique). The other records are also miss classified. In the data that produced the following table, 6 records were not sample uniques (score 0) and 4 had a score in the interval (0, 0.1] and not larger than 0.1 as in the table. The code below reproduces this example. The actual dis-suda scores are computed correctly.

```
> sdcInitial@risk$suda2$disScore
 [1] 0.000000000 0.000000000 0.005120313 0.000000000 0.010702061 0.000000000 0.005120313 0.008775093 0.000000000 0.000000000
> 
> # Summary of DIS-SUDA scores
> sdcInitial@risk$suda2

 Dis suda scores table: 
- - - - - - - - - - - 
  thresholds number
1        > 0      6
2      > 0.1      4
3      > 0.2      0
4      > 0.3      0
5      > 0.4      0
6      > 0.5      0
7      > 0.6      0
8      > 0.7      0
 - - - - - - - - - - - 
```

```
# Set up dataset
data <- as.data.frame(cbind(as.factor(c('a', 'a', 'a', 'a', 'b', 'a', 'a', 'a', 'a', 'a')),
                            as.factor(c('a', 'a', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'a')),
                            as.factor(c('a', 'a', 'b', 'c', 'c', 'c', 'd', 'e', 'a', 'a')),
                            as.factor(c('a', 'a', 'c', 'a', 'b', 'a', 'c', 'b', 'c', 'c')),
                            c(180, 180, 215, 76, 186, 76, 180, 215, 186, 76)))

names(data) <- c('V1', 'V2', 'V3', 'V4', 'V5')

# Set up sdcMicro object with specified quasi-identifiers
sdcInitial <- createSdcObj(dat = data, keyVars = c('V1', 'V2', 'V3', 'V4'), weightVar = 'V5')
sdcInitial

# Evaluating SUDA scores for the specified variables
sdcInitial <- suda2(obj = sdcInitial, missing = NA)

# DIS-SUDA scores
sdcInitial@risk$suda2$disScore

# Summary of DIS-SUDA scores
sdcInitial@risk$suda2
```

Furthermore, I would like to ask how missing values are treated in the SUDA algorithm: as being a category of their own, as replacing any value (as for k-anonymity) or in another way?

**Comment by bernhard-da** [comment]
hi @thijsbenschop 

thx for reporting. so this would be the output you would expect, right?

```
  thresholds number
1          0      6
2      > 0.0      4
3      > 0.1      0
4      > 0.2      0
5      > 0.3      0
6      > 0.4      0
7      > 0.5      0
8      > 0.6      0
9      > 0.7      0
```

**Comment by bernhard-da** [comment]
and to answer your second question. missing values (`NA`) are recoded into a category of their own before running the suda algorithm.

**Comment by thijsbenschop** [comment]
Thanks for your quick reply. Indeed, the output in your message is how I would expect it to be. Possibly, the first line with the number of records with zero scores could even be omitted, since little informative. 

Thanks for your reply on the treatment of missing values in the SUDA algorithm. Would it be possible/desirable to use the same treatment as for k-anonimity, i.e. NA is interpreted as any other value?
