### ISSUE TITLE
Error for method restr, correlated and ROMM in addNoise

### ISSUE THREAD

**Issue by matthias-da** [sdcTools/sdcMicro#93]
For method "correlated2" and "additive" everything works fine, but for methods "restr", "correlated" and "ROMM" we get an error: Error in `[.data.frame`(x, , variables) : undefined columns selected

``` r
data("EIA")
sdc <- createSdcObj(EIA,
                    keyVars = c("UTILNAME","STATE"), 
                    numVars = c("RESSALES", "COMSALES", "INDSALES", "OTHRSALES"))
## this is OK:
sdc <- addNoise(sdc, method = "correlated2")
sdc <- addNoise(sdc, method = "additive")
## but this gives errors (currently I don't know why)
sdc <- addNoise(sdc, method = "correlated")
## Error in `[.data.frame`(x, , variables) : undefined columns selected
sdc <- addNoise(sdc, "restr")
## Error in `[.data.frame`(x, , variables) : undefined columns selected
sdc <- addNoise(sdc, "ROMM")
## Error in `[.data.frame`(x, , variables) : undefined columns selected
```

**Comment by bernhard-da** [comment]
the two last commands do not work because of argument-matching.
`sdc <- addNoise(sdc, method="restr")` as well as `sdc <- addNoise(sdc, method="ROMM")` work. note the 'method=' call.

**Comment by matthias-da** [comment]
of course, I'm an idiot!

General question: how to debug, e.g., addNoiseWORK and addNoise,data.frame-method ?
It would then cost 3 seconds to get aware of my mistake, but without debug() it is time consuming to find the problem in our S4 class implementation.
